//! Immutable H0 production probe rows.

use super::{H0_PRODUCTION_PROBE_COUNT, ProbeId, ProbeSpec, ProbeTarget};
use peritus_security_policy::{AcceptanceCriterion, SecurityRequirement};

pub(super) const PROBES: [ProbeSpec; H0_PRODUCTION_PROBE_COUNT] = [
    probe(
        ProbeId::RepositoryTraversal,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec003,
        AcceptanceCriterion::Criterion9,
        "deny relative and absolute traversal outside the authorized repository root",
    ),
    probe(
        ProbeId::SymlinkRace,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec003,
        AcceptanceCriterion::Criterion9,
        "deny symlink replacement and time-of-check/time-of-use target escape",
    ),
    probe(
        ProbeId::SubmoduleEscape,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec003,
        AcceptanceCriterion::Criterion9,
        "contain malicious submodule paths and nested repository metadata",
    ),
    probe(
        ProbeId::WorktreeEscape,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec003,
        AcceptanceCriterion::Criterion9,
        "contain linked-worktree indirection and external gitdir targets",
    ),
    probe(
        ProbeId::CaseAliasCollision,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec003,
        AcceptanceCriterion::Criterion9,
        "reject case-folded aliases of protected and authorized paths",
    ),
    probe(
        ProbeId::DevicePath,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec003,
        AcceptanceCriterion::Criterion9,
        "reject Unix device nodes and Windows reserved or namespace device paths",
    ),
    probe(
        ProbeId::ShellInjection,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec001,
        AcceptanceCriterion::Criterion9,
        "prove repository text cannot become shell syntax or grant execution authority",
    ),
    probe(
        ProbeId::PoisonedRepositoryInstructions,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec006,
        AcceptanceCriterion::Criterion9,
        "preserve provenance and authority precedence under malicious repository instructions",
    ),
    probe(
        ProbeId::OversizedOutput,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec004,
        AcceptanceCriterion::Criterion9,
        "bound output ingestion and return explicit non-success under exhaustion",
    ),
    probe(
        ProbeId::TerminalEscape,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec006,
        AcceptanceCriterion::Criterion9,
        "sanitize terminal control and hyperlink sequences without corrupting evidence",
    ),
    probe(
        ProbeId::SecretExfiltration,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec004,
        AcceptanceCriterion::Criterion9,
        "deny filesystem network process and evidence paths for seeded secret exfiltration",
    ),
    probe(
        ProbeId::LinuxSandboxCapabilities,
        ProbeTarget::Linux,
        SecurityRequirement::RSec004,
        AcceptanceCriterion::Criterion10,
        "execute the common capability suite through the native Linux backend",
    ),
    probe(
        ProbeId::MacosSandboxCapabilities,
        ProbeTarget::Macos,
        SecurityRequirement::RSec004,
        AcceptanceCriterion::Criterion10,
        "execute the common capability suite through the native macOS backend",
    ),
    probe(
        ProbeId::WindowsSandboxCapabilities,
        ProbeTarget::Windows,
        SecurityRequirement::RSec004,
        AcceptanceCriterion::Criterion10,
        "execute the common capability suite through the native Windows backend",
    ),
    probe(
        ProbeId::SandboxEscape,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec004,
        AcceptanceCriterion::Criterion10,
        "exercise reviewed escape attempts against filesystem process network environment secret and resource controls",
    ),
    probe(
        ProbeId::NetworkDefaultDeny,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec004,
        AcceptanceCriterion::Criterion10,
        "prove native default-deny networking and exact destination allowlisting",
    ),
    probe(
        ProbeId::PluginCapabilityScope,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec007,
        AcceptanceCriterion::Criterion10,
        "deny untrusted plugin effects outside declared digest-bound capabilities",
    ),
    probe(
        ProbeId::McpCapabilityScope,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec002,
        AcceptanceCriterion::Criterion10,
        "deny MCP tool resource and prompt access outside current actor-bound authority",
    ),
    probe(
        ProbeId::ReviewerReadOnly,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec002,
        AcceptanceCriterion::Criterion11,
        "prove a reviewer cannot mutate candidate state or protected metadata",
    ),
    probe(
        ProbeId::FixerCannotApprove,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec002,
        AcceptanceCriterion::Criterion11,
        "prove a writable fixer cannot approve its own remediation",
    ),
    probe(
        ProbeId::WriterCannotWaive,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec002,
        AcceptanceCriterion::Criterion11,
        "prove a writer cannot waive findings produced against its candidate",
    ),
    probe(
        ProbeId::CandidateMutationInvalidation,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec005,
        AcceptanceCriterion::Criterion12,
        "prove any source artifact plan or revision mutation invalidates prior evidence",
    ),
    probe(
        ProbeId::SealedAnswerDenial,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec005,
        AcceptanceCriterion::Criterion17,
        "deny evolution candidates access to sealed evaluation answers",
    ),
    probe(
        ProbeId::EvaluatorMutationDenial,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec005,
        AcceptanceCriterion::Criterion17,
        "deny evolution candidates writes to evaluators and protected policy",
    ),
    probe(
        ProbeId::ProfileMutationDenial,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec002,
        AcceptanceCriterion::Criterion17,
        "deny model and resource profile mutation outside explicit authority",
    ),
    probe(
        ProbeId::SelfPromotionDenial,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec001,
        AcceptanceCriterion::Criterion17,
        "prove model output and candidate processes cannot promote themselves",
    ),
    probe(
        ProbeId::EvolutionCampaignIsolation,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec006,
        AcceptanceCriterion::Criterion17,
        "keep candidate baseline evaluator and external content provenance isolated",
    ),
    probe(
        ProbeId::PromotionGateBinding,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec002,
        AcceptanceCriterion::Criterion18,
        "bind every statistical correctness safety resource and authority gate to immutable candidate and baseline revisions",
    ),
    probe(
        ProbeId::AtomicRollbackHistory,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec005,
        AcceptanceCriterion::Criterion18,
        "prove atomic rollback while preserving candidate and baseline histories",
    ),
    probe(
        ProbeId::EvidenceCitation,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec006,
        AcceptanceCriterion::Criterion19,
        "require source event and artifact identifiers for security observations",
    ),
    probe(
        ProbeId::InfrastructureFailureTaxonomy,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec006,
        AcceptanceCriterion::Criterion19,
        "distinguish infrastructure failures from candidate security failures",
    ),
    probe(
        ProbeId::SecretRedaction,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec004,
        AcceptanceCriterion::Criterion19,
        "redact seeded secrets from default logs reports and exported evidence",
    ),
    probe(
        ProbeId::DependencyReproducibility,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec007,
        AcceptanceCriterion::Criterion24,
        "rebuild release dependencies from the locked graph and verify provenance",
    ),
    probe(
        ProbeId::ReleaseSignatureSbom,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec007,
        AcceptanceCriterion::Criterion24,
        "verify release signatures SBOM provenance and license notices",
    ),
    probe(
        ProbeId::MigrationRecoveryDocumentation,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec007,
        AcceptanceCriterion::Criterion24,
        "verify migration and recovery documentation accompanies release artifacts",
    ),
    probe(
        ProbeId::UnsafeInventory,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec005,
        AcceptanceCriterion::Criterion25,
        "reconcile every unsafe block with ownership safety justification and required Miri evidence",
    ),
    probe(
        ProbeId::TcbInventory,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec005,
        AcceptanceCriterion::Criterion25,
        "reconcile the trusted computing base and every trusted construct allowlist entry",
    ),
    probe(
        ProbeId::NoQuarantinedOrPlaceholderProduction,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec001,
        AcceptanceCriterion::Criterion25,
        "reject ignored failures quarantined tests and placeholder production implementations",
    ),
    probe(
        ProbeId::FindingLifecycle,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec007,
        AcceptanceCriterion::Criterion25,
        "reconcile findings through remediation and independent retest with no unresolved blocker",
    ),
    probe(
        ProbeId::CancellationAndTreeCleanup,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec004,
        AcceptanceCriterion::Criterion25,
        "cancel within bounds and remove the complete owned process file network and sandbox subject",
    ),
    probe(
        ProbeId::ThreatInventory,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec006,
        AcceptanceCriterion::Criterion25,
        "reconcile the versioned threat inventory with current assets boundaries owners and probes",
    ),
    probe(
        ProbeId::ControlInventory,
        ProbeTarget::TierOneHost,
        SecurityRequirement::RSec002,
        AcceptanceCriterion::Criterion25,
        "reconcile every R-SEC requirement and numbered criterion with controls owners and evidence",
    ),
];

const fn probe(
    id: ProbeId,
    target: ProbeTarget,
    requirement: SecurityRequirement,
    criterion: AcceptanceCriterion,
    description: &'static str,
) -> ProbeSpec {
    ProbeSpec::new(id, target, requirement, criterion, description)
}
