//! Command binding, result, and public error field metadata.

use super::super::super::{
    AppTypeDescriptor, CanonicalWireType, FieldBound as B, JsonShape as J, field,
};

pub(in crate::schema::fields::types) const COMMAND_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "CommandBinding",
        rust_type: "CommandBinding",
        fields: &[
            field(
                "actorId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "ActorId",
                "ActorId",
                J::Identifier,
                true,
            ),
            field(
                "sessionId",
                CanonicalWireType::Identifier,
                &[B::NonZero, B::EnvelopeBinding],
                "SessionId",
                "SessionId",
                J::Identifier,
                true,
            ),
            field(
                "requestId",
                CanonicalWireType::Identifier,
                &[B::NonZero, B::EnvelopeBinding],
                "RequestId",
                "RequestId",
                J::Identifier,
                true,
            ),
            field(
                "correlationId",
                CanonicalWireType::Identifier,
                &[B::NonZero, B::EnvelopeBinding],
                "CorrelationId",
                "CorrelationId",
                J::Identifier,
                true,
            ),
            field(
                "idempotencyKey",
                CanonicalWireType::Bytes,
                &[B::NonZero, B::IdempotencyKeyBytes],
                "IdempotencyKey",
                "Base64Bytes",
                J::Base64,
                true,
            ),
            field(
                "expectedRevision",
                CanonicalWireType::Option,
                &[],
                "Option<RevisionTuple>",
                "RevisionTuple",
                J::Ref("RevisionTuple"),
                false,
            ),
            field(
                "envelopeFrame",
                CanonicalWireType::Bytes,
                &[B::CodecFrameBytes],
                "ExactB3Frame",
                "Base64Bytes",
                J::Base64,
                true,
            ),
            field(
                "commandFrame",
                CanonicalWireType::Bytes,
                &[B::CodecFrameBytes],
                "ExactB3Frame",
                "Base64Bytes",
                J::Base64,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "CommittedEventRange",
        rust_type: "CommittedEventRange",
        fields: &[
            field(
                "first",
                CanonicalWireType::U64,
                &[B::NonZero, B::Contiguous],
                "EventCursor",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "last",
                CanonicalWireType::U64,
                &[B::NonZero, B::Contiguous],
                "EventCursor",
                "UInt64",
                J::U64String,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "AppProtocolError",
        rust_type: "AppProtocolError",
        fields: &[
            field(
                "code",
                CanonicalWireType::U16,
                &[],
                "AppErrorCode",
                "AppErrorCode",
                J::Ref("AppErrorCode"),
                true,
            ),
            field(
                "retry",
                CanonicalWireType::U8,
                &[],
                "RetryDisposition",
                "RetryDisposition",
                J::Enum(&["never", "same-request", "new-request", "after-recovery", "reconnect"]),
                true,
            ),
            field(
                "subsystem",
                CanonicalWireType::U8,
                &[],
                "ResponsibleSubsystem",
                "ResponsibleSubsystem",
                J::Enum(&[
                    "codec",
                    "negotiation",
                    "session",
                    "command",
                    "subscription",
                    "artifact",
                    "prompt",
                    "terminal",
                    "daemon",
                    "internal",
                ]),
                true,
            ),
            field(
                "diagnostic",
                CanonicalWireType::Option,
                &[B::DiagnosticBytes],
                "Option<AppDiagnostic>",
                "string",
                J::String,
                false,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "CommandResult",
        rust_type: "CommandResult",
        fields: &[
            field(
                "originalRequestId",
                CanonicalWireType::Identifier,
                &[B::NonZero, B::EnvelopeBinding],
                "RequestId",
                "RequestId",
                J::Identifier,
                true,
            ),
            field(
                "disposition",
                CanonicalWireType::U8,
                &[],
                "CommandDisposition",
                "\"committed\" | \"replayed\" | \"rejected\"",
                J::Enum(&["committed", "replayed", "rejected"]),
                true,
            ),
            field(
                "committedEvents",
                CanonicalWireType::Struct,
                &[B::Contiguous],
                "Option<CommittedEventRange>",
                "CommittedEventRange",
                J::Ref("CommittedEventRange"),
                false,
            ),
            field(
                "error",
                CanonicalWireType::Struct,
                &[],
                "Option<AppProtocolError>",
                "AppProtocolError",
                J::Ref("AppProtocolError"),
                false,
            ),
        ],
    },
];
