//! Subscription gap, acknowledgement, cancellation, and control field metadata.

use super::super::super::{
    AppTypeDescriptor, CanonicalWireType, FieldBound as B, JsonShape as J, field,
};

pub(in crate::schema::fields::types) const CONTROL_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "SubscriptionGapEvent",
        rust_type: "AppEventPayload::SubscriptionGap",
        fields: &[
            field(
                "subscriptionId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "SubscriptionId",
                "SubscriptionId",
                J::Identifier,
                true,
            ),
            field(
                "gap",
                CanonicalWireType::Struct,
                &[],
                "SubscriptionGap",
                "SubscriptionGap",
                J::Ref("SubscriptionGap"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "SubscriptionBackpressure",
        rust_type: "SubscriptionBackpressure",
        fields: &[
            field(
                "subscriptionId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "SubscriptionId",
                "SubscriptionId",
                J::Identifier,
                true,
            ),
            field(
                "lastDelivered",
                CanonicalWireType::U64,
                &[],
                "EventCursor",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "lastAcknowledged",
                CanonicalWireType::U64,
                &[B::Contiguous],
                "EventCursor",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maximumInFlight",
                CanonicalWireType::U32,
                &[B::NonZero, B::InFlightEvents],
                "u32",
                "number",
                J::U32,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "Acknowledgement",
        rust_type: "Acknowledgement",
        fields: &[
            field(
                "subscriptionId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "SubscriptionId",
                "SubscriptionId",
                J::Identifier,
                true,
            ),
            field(
                "cursor",
                CanonicalWireType::U64,
                &[B::Contiguous],
                "EventCursor",
                "UInt64",
                J::U64String,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "SubscriptionCancellation",
        rust_type: "SubscriptionCancellation",
        fields: &[
            field(
                "subscriptionId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "SubscriptionId",
                "SubscriptionId",
                J::Identifier,
                true,
            ),
            field(
                "correlationId",
                CanonicalWireType::Identifier,
                &[B::NonZero, B::EnvelopeBinding],
                "CorrelationId",
                "CorrelationId",
                J::Identifier,
                true,
            ),
            field(
                "source",
                CanonicalWireType::U8,
                &[],
                "SubscriptionCancellationSource",
                "\"client\" | \"server\"",
                J::Enum(&["client", "server"]),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "SubscriptionControl",
        rust_type: "SubscriptionControl",
        fields: &[
            field(
                "action",
                CanonicalWireType::U8,
                &[],
                "SubscriptionControl",
                "\"pause\" | \"resume\"",
                J::Enum(&["pause", "resume"]),
                true,
            ),
            field(
                "subscriptionId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "SubscriptionId",
                "SubscriptionId",
                J::Identifier,
                true,
            ),
            field(
                "reason",
                CanonicalWireType::U8,
                &[],
                "Option<PauseReason>",
                "\"client\" | \"slow-consumer\"",
                J::Enum(&["client", "slow-consumer"]),
                false,
            ),
        ],
    },
];
