//! Subscription request and delivery field metadata.

use super::super::super::{
    AppTypeDescriptor, CanonicalWireType, FieldBound as B, JsonShape as J, field,
};

pub(in crate::schema::fields::types) const DELIVERY_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "SubscriptionFilter",
        rust_type: "SubscriptionFilter",
        fields: &[field(
            "topics",
            CanonicalWireType::Sequence,
            &[B::Topics, B::CodecStringBytes, B::SortedUnique],
            "Vec<String>",
            "readonly string[]",
            J::StringArray,
            true,
        )],
    },
    AppTypeDescriptor {
        name: "SubscriptionRequest",
        rust_type: "SubscriptionRequest",
        fields: &[
            field(
                "subscriptionId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "SubscriptionId",
                "SubscriptionId",
                J::Identifier,
                true,
            ),
            field(
                "filter",
                CanonicalWireType::Struct,
                &[],
                "SubscriptionFilter",
                "SubscriptionFilter",
                J::Ref("SubscriptionFilter"),
                true,
            ),
            field(
                "after",
                CanonicalWireType::U64,
                &[],
                "EventCursor",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maximumInFlight",
                CanonicalWireType::U32,
                &[B::NonZero, B::InFlightEvents],
                "u32",
                "number",
                J::U32,
                true,
            ),
            field(
                "snapshotAcceptable",
                CanonicalWireType::Boolean,
                &[],
                "bool",
                "boolean",
                J::Boolean,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "SubscriptionStarted",
        rust_type: "SubscriptionStarted",
        fields: &[
            field(
                "subscriptionId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "SubscriptionId",
                "SubscriptionId",
                J::Identifier,
                true,
            ),
            field(
                "after",
                CanonicalWireType::U64,
                &[],
                "EventCursor",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maximumInFlight",
                CanonicalWireType::U32,
                &[B::NonZero, B::InFlightEvents],
                "u32",
                "number",
                J::U32,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "Delivery",
        rust_type: "Delivery",
        fields: &[
            field(
                "subscriptionId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "SubscriptionId",
                "SubscriptionId",
                J::Identifier,
                true,
            ),
            field(
                "eventId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "EventId",
                "EventId",
                J::Identifier,
                true,
            ),
            field(
                "cursor",
                CanonicalWireType::U64,
                &[B::NonZero, B::Contiguous],
                "EventCursor",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "attemptId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "DeliveryAttemptId",
                "DeliveryAttemptId",
                J::Identifier,
                true,
            ),
            field("attempt", CanonicalWireType::U32, &[B::NonZero], "u32", "number", J::U32, true),
            field(
                "frame",
                CanonicalWireType::Bytes,
                &[B::CodecFrameBytes],
                "RegisteredEventFrame",
                "Base64Bytes",
                J::Base64,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "SubscriptionGap",
        rust_type: "SubscriptionGap",
        fields: &[
            field(
                "requested",
                CanonicalWireType::U64,
                &[],
                "EventCursor",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "earliest",
                CanonicalWireType::U64,
                &[B::Contiguous],
                "EventCursor",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "latest",
                CanonicalWireType::U64,
                &[B::Contiguous],
                "EventCursor",
                "UInt64",
                J::U64String,
                true,
            ),
        ],
    },
];
