//! Exact brief wire fields and bounded user-input provenance.

use super::super::{
    AppFieldDescriptor, AppTypeDescriptor, CanonicalWireType as W, FieldBound as B, JsonShape as J,
    field,
};

const FIELD: AppFieldDescriptor = field(
    "field",
    W::U16,
    &[],
    "WorkbenchBriefField",
    "\"objective\" | \"acceptance\" | \"constraints\" | \"assumptions\"",
    J::Enum(&["objective", "acceptance", "constraints", "assumptions"]),
    true,
);

pub(super) const BRIEF_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "WorkbenchBriefIntent",
        rust_type: "WorkbenchIntent",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "WorkbenchIntent",
                "\"setBrief\"",
                J::Enum(&["setBrief"]),
                true,
            ),
            FIELD,
            field(
                "text",
                W::Utf8,
                &[B::WorkbenchInputBytes],
                "WorkbenchInputText",
                "string",
                J::String,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchBriefAcceptIntent",
        rust_type: "WorkbenchIntent",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "WorkbenchIntent",
                "\"acceptBriefProposal\"",
                J::Enum(&["acceptBriefProposal"]),
                true,
            ),
            FIELD,
            field(
                "proposal",
                W::Identifier,
                &[B::NonZero],
                "ControlOperationId",
                "ControlOperationId",
                J::Identifier,
                true,
            ),
            field("digest", W::Digest, &[], "Sha256Digest", "Sha256Digest", J::Digest, true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchBriefEntry",
        rust_type: "WorkbenchBriefEntry",
        fields: &[
            FIELD,
            field(
                "source",
                W::Struct,
                &[],
                "WorkbenchInputRow",
                "WorkbenchInputRow",
                J::Ref("WorkbenchInputRow"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchBriefProposal",
        rust_type: "WorkbenchBriefProposal",
        fields: &[
            field(
                "operation",
                W::Identifier,
                &[B::NonZero],
                "ControlOperationId",
                "ControlOperationId",
                J::Identifier,
                true,
            ),
            field(
                "invocation",
                W::Identifier,
                &[B::NonZero],
                "WorkbenchInvocationId",
                "WorkbenchInvocationId",
                J::Identifier,
                true,
            ),
            field("digest", W::Digest, &[], "Sha256Digest", "Sha256Digest", J::Digest, true),
            field(
                "text",
                W::Utf8,
                &[B::WorkbenchInputBytes],
                "WorkbenchInputText",
                "string",
                J::String,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchBriefObservation",
        rust_type: "WorkbenchBriefObservation",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "WorkbenchBriefObservationKind",
                "\"image\" | \"file\"",
                J::Enum(&["image", "file"]),
                true,
            ),
            field(
                "operation",
                W::Identifier,
                &[B::NonZero],
                "ControlOperationId",
                "ControlOperationId",
                J::Identifier,
                true,
            ),
            field("hasVersion", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field(
                "version",
                W::Identifier,
                &[B::NonZero],
                "ControlOperationId",
                "ControlOperationId",
                J::Identifier,
                false,
            ),
            field(
                "label",
                W::Utf8,
                &[B::WorkbenchFilePathBytes],
                "String",
                "string",
                J::String,
                true,
            ),
            field("digest", W::Digest, &[], "Sha256Digest", "Sha256Digest", J::Digest, true),
            field(
                "bytes",
                W::U64,
                &[B::WorkbenchContextSourceBytes],
                "u64",
                "UInt64",
                J::U64String,
                true,
            ),
            field("selected", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchBrief",
        rust_type: "WorkbenchBrief",
        fields: &[
            field(
                "query",
                W::Struct,
                &[],
                "WorkbenchQuery",
                "WorkbenchQuery",
                J::Ref("WorkbenchQuery"),
                true,
            ),
            field("revision", W::U64, &[B::NonZero], "u64", "UInt64", J::U64String, true),
            field(
                "entries",
                W::Sequence,
                &[B::WorkbenchBriefFields],
                "Vec<WorkbenchBriefEntry>",
                "readonly WorkbenchBriefEntry[]",
                J::ArrayRef("WorkbenchBriefEntry"),
                true,
            ),
            field(
                "proposals",
                W::Sequence,
                &[B::WorkbenchBriefProposals, B::SortedUnique],
                "Vec<WorkbenchBriefProposal>",
                "readonly WorkbenchBriefProposal[]",
                J::ArrayRef("WorkbenchBriefProposal"),
                true,
            ),
            field(
                "observations",
                W::Sequence,
                &[B::WorkbenchBriefObservations, B::SortedUnique],
                "Vec<WorkbenchBriefObservation>",
                "readonly WorkbenchBriefObservation[]",
                J::ArrayRef("WorkbenchBriefObservation"),
                true,
            ),
            field("excludedProposals", W::U32, &[], "u32", "number", J::U32, true),
        ],
    },
];
