//! Additive exact brief inventory and immutable UTF-8 body paging.
use super::super::{
    AppTypeDescriptor, CanonicalWireType as W, FieldBound as B, JsonShape as J, field,
};
pub(super) const BRIEF_PAGE_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "WorkbenchBriefPageRequest",
        rust_type: "WorkbenchBriefPageRequest",
        fields: &[
            field(
                "query",
                W::Struct,
                &[],
                "WorkbenchQuery",
                "WorkbenchQuery",
                J::Ref("WorkbenchQuery"),
                true,
            ),
            field("revision", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("proposals", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("observations", W::U64, &[], "u64", "UInt64", J::U64String, true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchBriefProposalReference",
        rust_type: "WorkbenchBriefProposalReference",
        fields: &[
            field(
                "operation",
                W::Identifier,
                &[B::NonZero],
                "ControlOperationId",
                "ControlOperationId",
                J::Identifier,
                true,
            ),
            field(
                "invocation",
                W::Identifier,
                &[B::NonZero],
                "WorkbenchInvocationId",
                "WorkbenchInvocationId",
                J::Identifier,
                true,
            ),
            field("digest", W::Digest, &[], "Sha256Digest", "Sha256Digest", J::Digest, true),
            field("bytes", W::U64, &[], "u64", "UInt64", J::U64String, true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchBriefPage",
        rust_type: "WorkbenchBriefPage",
        fields: &[
            field(
                "request",
                W::Struct,
                &[],
                "WorkbenchBriefPageRequest",
                "WorkbenchBriefPageRequest",
                J::Ref("WorkbenchBriefPageRequest"),
                true,
            ),
            field("revision", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field(
                "entries",
                W::Sequence,
                &[B::WorkbenchBriefFields],
                "Vec<WorkbenchBriefEntry>",
                "readonly WorkbenchBriefEntry[]",
                J::ArrayRef("WorkbenchBriefEntry"),
                true,
            ),
            field("proposalTotal", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field(
                "proposals",
                W::Sequence,
                &[B::WorkbenchBriefPageItems],
                "Vec<WorkbenchBriefProposalReference>",
                "readonly WorkbenchBriefProposalReference[]",
                J::ArrayRef("WorkbenchBriefProposalReference"),
                true,
            ),
            field("observationTotal", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field(
                "observations",
                W::Sequence,
                &[B::WorkbenchBriefPageItems],
                "Vec<WorkbenchBriefObservation>",
                "readonly WorkbenchBriefObservation[]",
                J::ArrayRef("WorkbenchBriefObservation"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchBriefProposalRequest",
        rust_type: "WorkbenchBriefProposalRequest",
        fields: &[
            field(
                "query",
                W::Struct,
                &[],
                "WorkbenchQuery",
                "WorkbenchQuery",
                J::Ref("WorkbenchQuery"),
                true,
            ),
            field("revision", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field(
                "proposal",
                W::Struct,
                &[],
                "WorkbenchBriefProposalReference",
                "WorkbenchBriefProposalReference",
                J::Ref("WorkbenchBriefProposalReference"),
                true,
            ),
            field("offset", W::U64, &[], "u64", "UInt64", J::U64String, true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchBriefProposalPage",
        rust_type: "WorkbenchBriefProposalPage",
        fields: &[
            field(
                "request",
                W::Struct,
                &[],
                "WorkbenchBriefProposalRequest",
                "WorkbenchBriefProposalRequest",
                J::Ref("WorkbenchBriefProposalRequest"),
                true,
            ),
            field(
                "text",
                W::Utf8,
                &[B::WorkbenchBriefBodyBytes],
                "String",
                "string",
                J::String,
                true,
            ),
        ],
    },
];
