//! Covered-path checkpoints, exact rewind previews, and durable restore receipts.

mod field_shapes;
use super::super::{
    AppTypeDescriptor, CanonicalWireType as W, FieldBound as B, JsonShape as J, field,
};
use field_shapes::{
    id, kind, nested, nested_optional, page_strings, path, revision, strings, u64_field, version,
};

pub(super) const CHECKPOINT_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "WorkbenchCheckpointAbsentVersion",
        rust_type: "WorkbenchCheckpointVersion",
        fields: &[field(
            "kind",
            W::U16,
            &[],
            "WorkbenchCheckpointVersion",
            "\"absent\"",
            J::Enum(&["absent"]),
            true,
        )],
    },
    AppTypeDescriptor {
        name: "WorkbenchCheckpointPresentVersion",
        rust_type: "WorkbenchCheckpointVersion",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "WorkbenchCheckpointVersion",
                "\"present\"",
                J::Enum(&["present"]),
                true,
            ),
            field("digest", W::Digest, &[], "Sha256Digest", "Sha256Digest", J::Digest, true),
            field("bytes", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field(
                "mode",
                W::U16,
                &[],
                "WorkbenchCheckpointFileMode",
                "\"regular\" | \"executable\"",
                J::Enum(&["regular", "executable"]),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchCheckpointReferences",
        rust_type: "WorkbenchCheckpointReferences",
        fields: &[
            revision("sourceConversationRevision", true),
            field("contextGeneration", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("briefRevision", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("hasGoalRevision", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            revision("goalRevision", false),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchCheckpointPath",
        rust_type: "WorkbenchCheckpointPath",
        fields: &[
            path("path"),
            version("checkpoint", true),
            field("hasExpectedCurrent", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            version("expectedCurrent", false),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchCheckpointReceipt",
        rust_type: "WorkbenchCheckpointReceipt",
        fields: &[
            id("checkpoint"),
            nested("query", "WorkbenchQuery"),
            revision("acceptedRevision", true),
            field(
                "name",
                W::Utf8,
                &[B::WorkbenchCheckpointNameBytes],
                "WorkbenchCheckpointName",
                "string",
                J::String,
                true,
            ),
            nested("references", "WorkbenchCheckpointReferences"),
            field(
                "paths",
                W::Sequence,
                &[B::WorkbenchCheckpointPaths, B::SortedUnique],
                "Vec<WorkbenchCheckpointPath>",
                "readonly WorkbenchCheckpointPath[]",
                J::ArrayRef("WorkbenchCheckpointPath"),
                true,
            ),
            strings("exclusions", false),
            strings("externalEffects", false),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchRewindRequest",
        rust_type: "WorkbenchRewindRequest",
        fields: &[
            nested("query", "WorkbenchQuery"),
            revision("revision", true),
            id("checkpoint"),
            field(
                "mode",
                W::U16,
                &[],
                "WorkbenchRewindMode",
                "\"files_only\" | \"conversation_only\" | \"combined\"",
                J::Enum(&["files_only", "conversation_only", "combined"]),
                true,
            ),
            field(
                "child",
                W::Identifier,
                &[B::NonZero],
                "Option<ConversationId>",
                "ConversationId",
                J::Identifier,
                false,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchRewindPath",
        rust_type: "WorkbenchRewindPath",
        fields: &[
            path("path"),
            version("checkpoint", true),
            field("hasExpectedCurrent", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            version("expectedCurrent", false),
            version("observedCurrent", true),
            field(
                "disposition",
                W::U16,
                &[],
                "WorkbenchRewindDisposition",
                "\"restore\" | \"unchanged\" | \"conflict\" | \"unsealed\"",
                J::Enum(&["restore", "unchanged", "conflict", "unsealed"]),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchRewindPreview",
        rust_type: "WorkbenchRewindPreview",
        fields: &[
            nested("request", "WorkbenchRewindRequest"),
            field("previewDigest", W::Digest, &[], "Sha256Digest", "Sha256Digest", J::Digest, true),
            field(
                "paths",
                W::Sequence,
                &[B::WorkbenchCheckpointPaths, B::SortedUnique],
                "Vec<WorkbenchRewindPath>",
                "readonly WorkbenchRewindPath[]",
                J::ArrayRef("WorkbenchRewindPath"),
                true,
            ),
            strings("exclusions", false),
            strings("externalEffects", false),
            field(
                "conversationHistoryPreserved",
                W::Boolean,
                &[],
                "bool",
                "boolean",
                J::Boolean,
                true,
            ),
            field("accountingPreserved", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchCreateCheckpointIntent",
        rust_type: "WorkbenchIntent",
        fields: &[
            kind("\"createCheckpoint\"", &["createCheckpoint"]),
            field(
                "name",
                W::Utf8,
                &[B::WorkbenchCheckpointNameBytes],
                "WorkbenchCheckpointName",
                "string",
                J::String,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchApplyRewindIntent",
        rust_type: "WorkbenchIntent",
        fields: &[
            kind("\"applyRewind\"", &["applyRewind"]),
            nested("preview", "WorkbenchRewindPreview"),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchRestoreReceipt",
        rust_type: "WorkbenchRestoreReceipt",
        fields: &[
            id("restore"),
            id("checkpoint"),
            id("recoveryCheckpoint"),
            nested("query", "WorkbenchQuery"),
            revision("acceptedRevision", true),
            field(
                "status",
                W::U16,
                &[],
                "WorkbenchRestoreStatus",
                "\"applied\" | \"conflict\" | \"recoveryRequired\"",
                J::Enum(&["applied", "conflict", "recoveryRequired"]),
                true,
            ),
            strings("restored", true),
            strings("conflicts", true),
            strings("externalEffects", true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchRewindConfirmation",
        rust_type: "WorkbenchRewindConfirmation",
        fields: &[
            nested("request", "WorkbenchRewindRequest"),
            field("previewDigest", W::Digest, &[], "Sha256Digest", "Sha256Digest", J::Digest, true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchConfirmRewindIntent",
        rust_type: "WorkbenchIntent",
        fields: &[
            kind("\"confirmRewind\"", &["confirmRewind"]),
            nested("confirmation", "WorkbenchRewindConfirmation"),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchCoverageCursor",
        rust_type: "WorkbenchCoverageCursor",
        fields: &[
            field(
                "section",
                W::U16,
                &[],
                "WorkbenchCoverageSection",
                "\"paths\" | \"exclusions\" | \"externalEffects\"",
                J::Enum(&["paths", "exclusions", "externalEffects"]),
                true,
            ),
            u64_field("offset"),
            field("fingerprint", W::Digest, &[], "Sha256Digest", "Sha256Digest", J::Digest, true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchCheckpointPageRequest",
        rust_type: "WorkbenchCheckpointPageRequest",
        fields: &[
            nested("query", "WorkbenchQuery"),
            revision("revision", true),
            id("checkpoint"),
            field("hasCursor", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            nested_optional("cursor", "WorkbenchCoverageCursor"),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchRewindPageRequest",
        rust_type: "WorkbenchRewindPageRequest",
        fields: &[
            nested("request", "WorkbenchRewindRequest"),
            field("hasCursor", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            nested_optional("cursor", "WorkbenchCoverageCursor"),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchCheckpointCoveragePage",
        rust_type: "WorkbenchCheckpointCoveragePage",
        fields: &[
            id("checkpoint"),
            nested("query", "WorkbenchQuery"),
            revision("selectedRevision", true),
            revision("acceptedRevision", true),
            field(
                "name",
                W::Utf8,
                &[B::WorkbenchCheckpointNameBytes],
                "WorkbenchCheckpointName",
                "string",
                J::String,
                true,
            ),
            nested("references", "WorkbenchCheckpointReferences"),
            field("fingerprint", W::Digest, &[], "Sha256Digest", "Sha256Digest", J::Digest, true),
            u64_field("totalPaths"),
            u64_field("totalExclusions"),
            u64_field("totalExternalEffects"),
            field(
                "section",
                W::U16,
                &[],
                "WorkbenchCoverageSection",
                "\"paths\" | \"exclusions\" | \"externalEffects\"",
                J::Enum(&["paths", "exclusions", "externalEffects"]),
                true,
            ),
            u64_field("offset"),
            field(
                "paths",
                W::Sequence,
                &[B::CodecCollectionItems, B::SortedUnique],
                "Vec<WorkbenchCheckpointPath>",
                "readonly WorkbenchCheckpointPath[]",
                J::ArrayRef("WorkbenchCheckpointPath"),
                true,
            ),
            page_strings("exclusions"),
            page_strings("externalEffects"),
            field("hasNext", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            nested_optional("next", "WorkbenchCoverageCursor"),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchRewindCoveragePage",
        rust_type: "WorkbenchRewindCoveragePage",
        fields: &[
            nested("confirmation", "WorkbenchRewindConfirmation"),
            u64_field("totalPaths"),
            u64_field("totalExclusions"),
            u64_field("totalExternalEffects"),
            field(
                "section",
                W::U16,
                &[],
                "WorkbenchCoverageSection",
                "\"paths\" | \"exclusions\" | \"externalEffects\"",
                J::Enum(&["paths", "exclusions", "externalEffects"]),
                true,
            ),
            u64_field("offset"),
            field(
                "paths",
                W::Sequence,
                &[B::CodecCollectionItems, B::SortedUnique],
                "Vec<WorkbenchRewindPath>",
                "readonly WorkbenchRewindPath[]",
                J::ArrayRef("WorkbenchRewindPath"),
                true,
            ),
            page_strings("exclusions"),
            page_strings("externalEffects"),
            field("hasNext", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            nested_optional("next", "WorkbenchCoverageCursor"),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchRestoreSummary",
        rust_type: "WorkbenchRestoreSummary",
        fields: &[
            id("restore"),
            id("checkpoint"),
            id("recoveryCheckpoint"),
            nested("query", "WorkbenchQuery"),
            revision("acceptedRevision", true),
            field(
                "status",
                W::U16,
                &[],
                "WorkbenchRestoreStatus",
                "\"applied\" | \"conflict\" | \"recoveryRequired\"",
                J::Enum(&["applied", "conflict", "recoveryRequired"]),
                true,
            ),
            u64_field("restoredPaths"),
            u64_field("conflictingPaths"),
            field("fingerprint", W::Digest, &[], "Sha256Digest", "Sha256Digest", J::Digest, true),
        ],
    },
];
