//! Daemon, heartbeat, and shutdown flow field metadata.

use super::super::{AppTypeDescriptor, CanonicalWireType, FieldBound as B, JsonShape as J, field};

pub(super) const DAEMON_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "DaemonStatus",
        rust_type: "DaemonStatus",
        fields: &[
            field(
                "readiness",
                CanonicalWireType::U8,
                &[],
                "DaemonReadiness",
                "DaemonReadiness",
                J::Enum(&[
                    "starting",
                    "ready-read-write",
                    "ready-read-only",
                    "draining",
                    "unavailable",
                ]),
                true,
            ),
            field(
                "diagnostic",
                CanonicalWireType::Option,
                &[B::DiagnosticBytes],
                "Option<String>",
                "string",
                J::String,
                false,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "DaemonHeartbeat",
        rust_type: "DaemonHeartbeat",
        fields: &[
            field(
                "heartbeatId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "HeartbeatId",
                "HeartbeatId",
                J::Identifier,
                true,
            ),
            field(
                "sequence",
                CanonicalWireType::U64,
                &[B::Contiguous],
                "u64",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "status",
                CanonicalWireType::Struct,
                &[],
                "DaemonStatus",
                "DaemonStatus",
                J::Ref("DaemonStatus"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ShutdownRequest",
        rust_type: "ShutdownRequest",
        fields: &[
            field(
                "requestId",
                CanonicalWireType::Identifier,
                &[B::NonZero, B::EnvelopeBinding],
                "RequestId",
                "RequestId",
                J::Identifier,
                true,
            ),
            field(
                "correlationId",
                CanonicalWireType::Identifier,
                &[B::NonZero, B::EnvelopeBinding],
                "CorrelationId",
                "CorrelationId",
                J::Identifier,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "RemainingWork",
        rust_type: "RemainingWork",
        fields: &[
            field(
                "kind",
                CanonicalWireType::U8,
                &[],
                "RemainingWorkKind",
                "\"request\" | \"subscription\" | \"artifact-transfer\" | \"terminal-attachment\" | \"other\"",
                J::Enum(&[
                    "request",
                    "subscription",
                    "artifact-transfer",
                    "terminal-attachment",
                    "other",
                ]),
                true,
            ),
            field(
                "descriptor",
                CanonicalWireType::Utf8,
                &[B::DiagnosticBytes],
                "String",
                "string",
                J::String,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ShutdownProgress",
        rust_type: "ShutdownProgress",
        fields: &[
            field(
                "request",
                CanonicalWireType::Struct,
                &[],
                "ShutdownRequest",
                "ShutdownRequest",
                J::Ref("ShutdownRequest"),
                true,
            ),
            field("completedSteps", CanonicalWireType::U32, &[], "u32", "number", J::U32, true),
            field("totalSteps", CanonicalWireType::U32, &[], "u32", "number", J::U32, true),
            field(
                "remaining",
                CanonicalWireType::Sequence,
                &[B::RemainingWorkItems],
                "Vec<RemainingWork>",
                "readonly RemainingWork[]",
                J::ArrayRef("RemainingWork"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ShutdownComplete",
        rust_type: "ShutdownComplete",
        fields: &[
            field(
                "request",
                CanonicalWireType::Struct,
                &[],
                "ShutdownRequest",
                "ShutdownRequest",
                J::Ref("ShutdownRequest"),
                true,
            ),
            field(
                "disposition",
                CanonicalWireType::U8,
                &[],
                "ShutdownCompletionDisposition",
                "\"clean\" | \"unclean\"",
                J::Enum(&["clean", "unclean"]),
                true,
            ),
            field(
                "remaining",
                CanonicalWireType::Sequence,
                &[B::RemainingWorkItems],
                "Vec<RemainingWork>",
                "readonly RemainingWork[]",
                J::ArrayRef("RemainingWork"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "HeartbeatReply",
        rust_type: "HeartbeatReply",
        fields: &[
            field(
                "heartbeatId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "HeartbeatId",
                "HeartbeatId",
                J::Identifier,
                true,
            ),
            field(
                "sequence",
                CanonicalWireType::U64,
                &[B::Contiguous],
                "u64",
                "UInt64",
                J::U64String,
                true,
            ),
        ],
    },
];
