//! Bounded persistent-goal definitions, controls, evidence, and cumulative accounting.

use super::super::{
    AppFieldDescriptor, AppTypeDescriptor, CanonicalWireType as W, FieldBound as B, JsonShape as J,
    field,
};

const fn goal_id() -> AppFieldDescriptor {
    field(
        "goal",
        W::Identifier,
        &[B::NonZero],
        "ControlOperationId",
        "ControlOperationId",
        J::Identifier,
        true,
    )
}

const fn optional_u64(name: &'static str) -> AppFieldDescriptor {
    field(name, W::Option, &[B::NonZero], "Option<u64>", "UInt64", J::U64String, false)
}

const fn optional_u32(name: &'static str) -> AppFieldDescriptor {
    field(name, W::Option, &[B::NonZero], "Option<u32>", "number", J::U32, false)
}

pub(super) const GOAL_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "WorkbenchGoalBudget",
        rust_type: "WorkbenchGoalBudget",
        fields: &[
            optional_u64("maxActiveMillis"),
            optional_u32("maxRequests"),
            optional_u32("maxToolCalls"),
            optional_u64("maxTotalTokens"),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchGoalCriterionDefinition",
        rust_type: "WorkbenchGoalCriterionDefinition",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "WorkbenchGoalCriterionKind",
                "\"runnerAcceptance\" | \"graphicalPlaytest\" | \"humanValidation\"",
                J::Enum(&["runnerAcceptance", "graphicalPlaytest", "humanValidation"]),
                true,
            ),
            field(
                "description",
                W::Utf8,
                &[B::WorkbenchInputBytes],
                "WorkbenchInputText",
                "string",
                J::String,
                true,
            ),
            field("mandatory", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchGoalDefinition",
        rust_type: "WorkbenchGoalDefinition",
        fields: &[
            field(
                "objective",
                W::Utf8,
                &[B::WorkbenchInputBytes],
                "WorkbenchInputText",
                "string",
                J::String,
                true,
            ),
            field(
                "criteria",
                W::Sequence,
                &[B::WorkbenchGoalCriteria],
                "Vec<WorkbenchGoalCriterionDefinition>",
                "readonly WorkbenchGoalCriterionDefinition[]",
                J::ArrayRef("WorkbenchGoalCriterionDefinition"),
                true,
            ),
            field(
                "budget",
                W::Struct,
                &[],
                "WorkbenchGoalBudget",
                "WorkbenchGoalBudget",
                J::Ref("WorkbenchGoalBudget"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchStartGoalIntent",
        rust_type: "WorkbenchIntent",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "WorkbenchIntent",
                "\"startGoal\"",
                J::Enum(&["startGoal"]),
                true,
            ),
            field(
                "definition",
                W::Struct,
                &[],
                "WorkbenchGoalDefinition",
                "WorkbenchGoalDefinition",
                J::Ref("WorkbenchGoalDefinition"),
                true,
            ),
            field(
                "settings",
                W::Struct,
                &[],
                "WorkbenchExecutionSettings",
                "WorkbenchExecutionSettings",
                J::Ref("WorkbenchExecutionSettings"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchPauseGoalIntent",
        rust_type: "WorkbenchIntent",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "WorkbenchIntent",
                "\"pauseGoal\"",
                J::Enum(&["pauseGoal"]),
                true,
            ),
            goal_id(),
            field(
                "mode",
                W::U16,
                &[],
                "WorkbenchGoalPauseMode",
                "\"now\" | \"afterOperation\" | \"beforeEdit\"",
                J::Enum(&["now", "afterOperation", "beforeEdit"]),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchResumeOrClearGoalIntent",
        rust_type: "WorkbenchIntent",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "WorkbenchIntent",
                "\"resumeGoal\" | \"clearGoal\"",
                J::Enum(&["resumeGoal", "clearGoal"]),
                true,
            ),
            goal_id(),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchUpdateGoalBudgetIntent",
        rust_type: "WorkbenchIntent",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "WorkbenchIntent",
                "\"updateGoalBudget\"",
                J::Enum(&["updateGoalBudget"]),
                true,
            ),
            goal_id(),
            field(
                "budget",
                W::Struct,
                &[],
                "WorkbenchGoalBudget",
                "WorkbenchGoalBudget",
                J::Ref("WorkbenchGoalBudget"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchGoalCriterion",
        rust_type: "WorkbenchGoalCriterion",
        fields: &[
            field(
                "definition",
                W::Struct,
                &[],
                "WorkbenchGoalCriterionDefinition",
                "WorkbenchGoalCriterionDefinition",
                J::Ref("WorkbenchGoalCriterionDefinition"),
                true,
            ),
            field(
                "state",
                W::U16,
                &[],
                "WorkbenchGoalCriterionState",
                "\"pending\" | \"satisfied\" | \"unavailable\" | \"stale\"",
                J::Enum(&["pending", "satisfied", "unavailable", "stale"]),
                true,
            ),
            field("evidenceRevision", W::Option, &[], "Option<u64>", "UInt64", J::U64String, false),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchGoalRoleUsage",
        rust_type: "WorkbenchGoalRoleUsage",
        fields: &[
            field(
                "role",
                W::U16,
                &[],
                "WorkbenchGoalRole",
                "\"writer\" | \"reviewer\" | \"fixer\"",
                J::Enum(&["writer", "reviewer", "fixer"]),
                true,
            ),
            field("requests", W::U32, &[], "u32", "number", J::U32, true),
            field("completedRequests", W::U32, &[], "u32", "number", J::U32, true),
            field("toolCalls", W::U32, &[], "u32", "number", J::U32, true),
            field("totalTokens", W::Option, &[], "Option<u64>", "UInt64", J::U64String, false),
            field(
                "providerCostMicrounits",
                W::Option,
                &[],
                "Option<u64>",
                "UInt64",
                J::U64String,
                false,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchGoalUsage",
        rust_type: "WorkbenchGoalUsage",
        fields: &[
            field(
                "roles",
                W::Struct,
                &[B::WorkbenchGoalRoles],
                "[WorkbenchGoalRoleUsage; 3]",
                "readonly WorkbenchGoalRoleUsage[]",
                J::ArrayRef("WorkbenchGoalRoleUsage"),
                true,
            ),
            field("activeMillis", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("wallMillis", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("retries", W::U32, &[], "u32", "number", J::U32, true),
            field("providerFailovers", W::U32, &[], "u32", "number", J::U32, true),
            field("compactions", W::U32, &[], "u32", "number", J::U32, true),
            field("workspaceBytes", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("workspaceGrowthBytes", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("peakRssBytes", W::U64, &[], "u64", "UInt64", J::U64String, true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchGoalSnapshot",
        rust_type: "WorkbenchGoalSnapshot",
        fields: &[
            field(
                "query",
                W::Struct,
                &[],
                "WorkbenchQuery",
                "WorkbenchQuery",
                J::Ref("WorkbenchQuery"),
                true,
            ),
            field("aggregateRevision", W::U64, &[B::NonZero], "u64", "UInt64", J::U64String, true),
            goal_id(),
            field("run", W::Identifier, &[B::NonZero], "RunId", "RunId", J::Identifier, true),
            field(
                "objective",
                W::Utf8,
                &[B::WorkbenchInputBytes],
                "WorkbenchInputText",
                "string",
                J::String,
                true,
            ),
            field(
                "state",
                W::U16,
                &[],
                "WorkbenchGoalState",
                "\"active\" | \"waitingForUser\" | \"pausing\" | \"paused\" | \"blocked\" | \"budgetReached\" | \"achieved\" | \"cancelled\"",
                J::Enum(&[
                    "active",
                    "waitingForUser",
                    "pausing",
                    "paused",
                    "blocked",
                    "budgetReached",
                    "achieved",
                    "cancelled",
                ]),
                true,
            ),
            field(
                "reason",
                W::Utf8,
                &[B::WorkbenchGoalReasonBytes],
                "String",
                "string",
                J::String,
                true,
            ),
            field("userRevision", W::U64, &[B::NonZero], "u64", "UInt64", J::U64String, true),
            field("attempt", W::U32, &[B::NonZero], "u32", "number", J::U32, true),
            field("restartEligible", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field(
                "pauseMode",
                W::Option,
                &[],
                "Option<WorkbenchGoalPauseMode>",
                "\"now\" | \"afterOperation\" | \"beforeEdit\"",
                J::Enum(&["now", "afterOperation", "beforeEdit"]),
                false,
            ),
            field(
                "criteria",
                W::Sequence,
                &[B::WorkbenchGoalCriteria],
                "Vec<WorkbenchGoalCriterion>",
                "readonly WorkbenchGoalCriterion[]",
                J::ArrayRef("WorkbenchGoalCriterion"),
                true,
            ),
            field(
                "budget",
                W::Struct,
                &[],
                "WorkbenchGoalBudget",
                "WorkbenchGoalBudget",
                J::Ref("WorkbenchGoalBudget"),
                true,
            ),
            field(
                "usage",
                W::Struct,
                &[],
                "WorkbenchGoalUsage",
                "WorkbenchGoalUsage",
                J::Ref("WorkbenchGoalUsage"),
                true,
            ),
        ],
    },
];
