//! Conversation and model discovery metadata in canonical wire order.

use super::super::{
    AppTypeDescriptor, CanonicalWireType as W, FieldBound as B, JsonShape as J, field,
};

pub(super) const INTERACTION_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "ProductModelUpdate",
        rust_type: "ProductModelUpdate",
        fields: &[
            field("runId", W::Identifier, &[B::NonZero], "RunId", "RunId", J::Identifier, true),
            field(
                "models",
                W::Struct,
                &[],
                "ProductRoleModels",
                "ProductRoleModels",
                J::Ref("ProductRoleModels"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductModelChoice",
        rust_type: "ProductModelChoice",
        fields: &[
            field("id", W::Utf8, &[B::ProductModelBytes], "String", "string", J::String, true),
            field("manual", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            // Present for every role only in request tags 26/27 and response tag 17.
            // Legacy tags retain the exact id/manual pair and imply default effort.
            field(
                "effort",
                W::U16,
                &[],
                "ProductModelEffort",
                "\"default\" | \"minimal\" | \"low\" | \"medium\" | \"high\" | \"xhigh\" | \"max\" | \"ultra\"",
                J::Enum(&["default", "minimal", "low", "medium", "high", "xhigh", "max", "ultra"]),
                false,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductRoleModels",
        rust_type: "ProductRoleModels",
        fields: &[
            field(
                "writer",
                W::Struct,
                &[],
                "ProductModelChoice",
                "ProductModelChoice",
                J::Ref("ProductModelChoice"),
                true,
            ),
            field(
                "reviewer",
                W::Struct,
                &[],
                "ProductModelChoice",
                "ProductModelChoice",
                J::Ref("ProductModelChoice"),
                true,
            ),
            field(
                "fixer",
                W::Struct,
                &[],
                "ProductModelChoice",
                "ProductModelChoice",
                J::Ref("ProductModelChoice"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductActivity",
        rust_type: "ProductActivity",
        fields: &[
            field("sequence", W::U64, &[B::NonZero], "u64", "UInt64", J::U64String, true),
            field(
                "kind",
                W::U16,
                &[],
                "ProductActivityKind",
                "\"user\" | \"assistant\" | \"tool\" | \"status\" | \"error\"",
                J::Enum(&["user", "assistant", "tool", "status", "error"]),
                true,
            ),
            field("text", W::Utf8, &[B::ProductActivityBytes], "String", "string", J::String, true),
            field(
                "detail",
                W::Utf8,
                &[B::ProductActivityBytes],
                "String",
                "string",
                J::String,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductInteractionSnapshot",
        rust_type: "ProductInteractionSnapshot",
        fields: &[
            // The tag selects settled candidate facts or the current unsettled run state.
            field("settled", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field(
                "state",
                W::Struct,
                &[],
                "ProductRunSnapshot | ProductRunSettlementSnapshot",
                "ProductRunSnapshot | ProductRunSettlementSnapshot",
                J::OneOfRef(&["ProductRunSnapshot", "ProductRunSettlementSnapshot"]),
                true,
            ),
            field(
                "mode",
                W::U16,
                &[],
                "ProductInteractionMode",
                "\"chat\" | \"plan\" | \"review\" | \"build\"",
                J::Enum(&["chat", "plan", "review", "build"]),
                true,
            ),
            field(
                "models",
                W::Struct,
                &[],
                "ProductRoleModels",
                "ProductRoleModels",
                J::Ref("ProductRoleModels"),
                true,
            ),
            field("received", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("incorporated", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field(
                "activities",
                W::Sequence,
                &[B::ProductActivities, B::SortedUnique],
                "Vec<ProductActivity>",
                "readonly ProductActivity[]",
                J::ArrayRef("ProductActivity"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductActivityPreview",
        rust_type: "ProductActivity",
        fields: &[
            field("sequence", W::U64, &[B::NonZero], "u64", "UInt64", J::U64String, true),
            field(
                "kind",
                W::U16,
                &[],
                "ProductActivityKind",
                "\"user\" | \"assistant\" | \"tool\" | \"status\" | \"error\"",
                J::Enum(&["user", "assistant", "tool", "status", "error"]),
                true,
            ),
            field("text", W::Utf8, &[B::ProductActivityBytes], "String", "string", J::String, true),
            field("textBytes", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("detail", W::Utf8, &[B::ProductActivityBytes], "String", "string", J::String, true),
            field("detailBytes", W::U64, &[], "u64", "UInt64", J::U64String, true),
        ],
    },
    AppTypeDescriptor {
        name: "ProductActivityPageCursor",
        rust_type: "ProductActivityPageCursor",
        fields: &[
            field("runId", W::Identifier, &[B::NonZero], "RunId", "RunId", J::Identifier, true),
            field("history", W::Digest, &[], "Sha256Digest", "Sha256Digest", J::Digest, true),
            field("afterSequence", W::U64, &[B::NonZero], "u64", "UInt64", J::U64String, true),
            field("afterSegment", W::U64, &[], "u64", "UInt64", J::U64String, true),
        ],
    },
    AppTypeDescriptor {
        name: "ProductActivityPageQuery",
        rust_type: "ProductActivityPageQuery",
        fields: &[
            field("runId", W::Identifier, &[B::NonZero], "RunId", "RunId", J::Identifier, true),
            field("hasCursor", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field(
                "cursor",
                W::Conditional,
                &[B::EnvelopeBinding],
                "Option<ProductActivityPageCursor>",
                "ProductActivityPageCursor",
                J::Ref("ProductActivityPageCursor"),
                false,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductInteractionHistorySnapshot",
        rust_type: "ProductInteractionSnapshot",
        fields: &[
            field("settled", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field(
                "state",
                W::Struct,
                &[],
                "ProductRunSnapshot | ProductRunSettlementSnapshot",
                "ProductRunSnapshot | ProductRunSettlementSnapshot",
                J::OneOfRef(&["ProductRunSnapshot", "ProductRunSettlementSnapshot"]),
                true,
            ),
            field(
                "mode",
                W::U16,
                &[],
                "ProductInteractionMode",
                "\"chat\" | \"plan\" | \"review\" | \"build\"",
                J::Enum(&["chat", "plan", "review", "build"]),
                true,
            ),
            field("models", W::Struct, &[], "ProductRoleModels", "ProductRoleModels", J::Ref("ProductRoleModels"), true),
            field("received", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("incorporated", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field(
                "activities",
                W::Sequence,
                &[B::ProductActivities, B::SortedUnique],
                "Vec<ProductActivity>",
                "readonly ProductActivityPreview[]",
                J::ArrayRef("ProductActivityPreview"),
                true,
            ),
            field("history", W::Digest, &[], "Sha256Digest", "Sha256Digest", J::Digest, true),
            field("total", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("omitted", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("omittedErrors", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field(
                "retainedErrors",
                W::Sequence,
                &[B::ProductRetainedErrors, B::SortedUnique],
                "Vec<ProductActivity>",
                "readonly ProductActivityPreview[]",
                J::ArrayRef("ProductActivityPreview"),
                true,
            ),
            field("hasTerminalError", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field(
                "terminalError",
                W::Conditional,
                &[],
                "Option<ProductActivity>",
                "ProductActivityPreview",
                J::Ref("ProductActivityPreview"),
                false,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductActivitySegment",
        rust_type: "ProductActivitySegment",
        fields: &[
            field("sequence", W::U64, &[B::NonZero], "u64", "UInt64", J::U64String, true),
            field("segment", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field(
                "kind",
                W::U16,
                &[],
                "ProductActivityKind",
                "\"user\" | \"assistant\" | \"tool\" | \"status\" | \"error\"",
                J::Enum(&["user", "assistant", "tool", "status", "error"]),
                true,
            ),
            field("textOffset", W::U64, &[B::Contiguous], "u64", "UInt64", J::U64String, true),
            field("text", W::Utf8, &[B::ProductActivitySegmentBytes], "String", "string", J::String, true),
            field("textBytes", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("detailOffset", W::U64, &[B::Contiguous], "u64", "UInt64", J::U64String, true),
            field("detail", W::Utf8, &[B::ProductActivitySegmentBytes], "String", "string", J::String, true),
            field("detailBytes", W::U64, &[], "u64", "UInt64", J::U64String, true),
        ],
    },
    AppTypeDescriptor {
        name: "ProductInteractionPage",
        rust_type: "ProductInteractionPage",
        fields: &[
            field("query", W::Struct, &[], "ProductActivityPageQuery", "ProductActivityPageQuery", J::Ref("ProductActivityPageQuery"), true),
            field("interaction", W::Struct, &[], "ProductInteractionSnapshot", "ProductInteractionHistorySnapshot", J::Ref("ProductInteractionHistorySnapshot"), true),
            field(
                "segments",
                W::Sequence,
                &[B::ProductActivityPageSegments, B::SortedUnique, B::Contiguous],
                "Vec<ProductActivitySegment>",
                "readonly ProductActivitySegment[]",
                J::ArrayRef("ProductActivitySegment"),
                true,
            ),
            field("hasNext", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field(
                "next",
                W::Conditional,
                &[B::EnvelopeBinding],
                "Option<ProductActivityPageCursor>",
                "ProductActivityPageCursor",
                J::Ref("ProductActivityPageCursor"),
                false,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductModelQuery",
        rust_type: "ProductModelQuery",
        fields: &[
            field(
                "profile",
                W::Identifier,
                &[B::NonZero],
                "ProviderProfileId",
                "ProviderProfileId",
                J::Identifier,
                true,
            ),
            field("refresh", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
        ],
    },
    AppTypeDescriptor {
        name: "ProductModelInfo",
        rust_type: "ProductModelInfo",
        fields: &[
            field("id", W::Utf8, &[B::ProductModelBytes], "String", "string", J::String, true),
            field("label", W::Utf8, &[B::ProductModelBytes], "String", "string", J::String, true),
            field("tools", W::Option, &[], "Option<bool>", "boolean", J::Boolean, false),
        ],
    },
    AppTypeDescriptor {
        name: "ProductModelCatalog",
        rust_type: "ProductModelCatalog",
        fields: &[
            field(
                "profile",
                W::Identifier,
                &[B::NonZero],
                "ProviderProfileId",
                "ProviderProfileId",
                J::Identifier,
                true,
            ),
            field(
                "configured",
                W::Utf8,
                &[B::ProductModelBytes],
                "String",
                "string",
                J::String,
                true,
            ),
            field("fetchedUnixSeconds", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("cached", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field("error", W::Utf8, &[B::DiagnosticBytes], "String", "string", J::String, true),
            field(
                "models",
                W::Sequence,
                &[B::ProductModels],
                "Vec<ProductModelInfo>",
                "readonly ProductModelInfo[]",
                J::ArrayRef("ProductModelInfo"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductInteractionBinding",
        rust_type: "ProductInteractionBinding",
        fields: &[
            field("hasEffort", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field(
                "interaction",
                W::Struct,
                &[],
                "ProductInteractionSnapshot",
                "ProductInteractionSnapshot",
                J::Ref("ProductInteractionSnapshot"),
                true,
            ),
            field(
                "conversation",
                W::Option,
                &[],
                "Option<WorkbenchQuery>",
                "WorkbenchQuery",
                J::Ref("WorkbenchQuery"),
                false,
            ),
        ],
    },
];
