//! Conversation and model discovery metadata in canonical wire order.

use super::super::{
    AppTypeDescriptor, CanonicalWireType as W, FieldBound as B, JsonShape as J, field,
};

pub(super) const INTERACTION_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "ProductModelUpdate",
        rust_type: "ProductModelUpdate",
        fields: &[
            field("runId", W::Identifier, &[B::NonZero], "RunId", "RunId", J::Identifier, true),
            field(
                "models",
                W::Struct,
                &[],
                "ProductRoleModels",
                "ProductRoleModels",
                J::Ref("ProductRoleModels"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductRunRequest",
        rust_type: "ProductRunRequest",
        fields: &[
            field("runId", W::Identifier, &[B::NonZero], "RunId", "RunId", J::Identifier, true),
            field(
                "workspaceId",
                W::Identifier,
                &[B::NonZero],
                "WorkspaceId",
                "WorkspaceId",
                J::Identifier,
                true,
            ),
            field(
                "providers",
                W::Struct,
                &[],
                "ProductProviderSelection",
                "ProductProviderSelection",
                J::Ref("ProductProviderSelection"),
                true,
            ),
            field("task", W::Utf8, &[B::ProductTaskBytes], "String", "string", J::String, true),
        ],
    },
    AppTypeDescriptor {
        name: "ProductModelChoice",
        rust_type: "ProductModelChoice",
        fields: &[
            field("id", W::Utf8, &[B::ProductModelBytes], "String", "string", J::String, true),
            field("manual", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
        ],
    },
    AppTypeDescriptor {
        name: "ProductRoleModels",
        rust_type: "ProductRoleModels",
        fields: &[
            field(
                "writer",
                W::Struct,
                &[],
                "ProductModelChoice",
                "ProductModelChoice",
                J::Ref("ProductModelChoice"),
                true,
            ),
            field(
                "reviewer",
                W::Struct,
                &[],
                "ProductModelChoice",
                "ProductModelChoice",
                J::Ref("ProductModelChoice"),
                true,
            ),
            field(
                "fixer",
                W::Struct,
                &[],
                "ProductModelChoice",
                "ProductModelChoice",
                J::Ref("ProductModelChoice"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductInteractionRequest",
        rust_type: "ProductInteractionRequest",
        fields: &[
            field(
                "request",
                W::Struct,
                &[],
                "ProductRunRequest",
                "ProductRunRequest",
                J::Ref("ProductRunRequest"),
                true,
            ),
            field(
                "mode",
                W::U16,
                &[],
                "ProductInteractionMode",
                "\"chat\" | \"plan\" | \"review\" | \"build\"",
                J::Enum(&["chat", "plan", "review", "build"]),
                true,
            ),
            field(
                "models",
                W::Struct,
                &[],
                "ProductRoleModels",
                "ProductRoleModels",
                J::Ref("ProductRoleModels"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductActivity",
        rust_type: "ProductActivity",
        fields: &[
            field("sequence", W::U64, &[B::NonZero], "u64", "UInt64", J::U64String, true),
            field(
                "kind",
                W::U16,
                &[],
                "ProductActivityKind",
                "\"user\" | \"assistant\" | \"tool\" | \"status\" | \"error\"",
                J::Enum(&["user", "assistant", "tool", "status", "error"]),
                true,
            ),
            field("text", W::Utf8, &[B::ProductActivityBytes], "String", "string", J::String, true),
            field(
                "detail",
                W::Utf8,
                &[B::ProductActivityBytes],
                "String",
                "string",
                J::String,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductInteractionSnapshot",
        rust_type: "ProductInteractionSnapshot",
        fields: &[
            // The tag selects a full typed settlement snapshot or an unsettled legacy snapshot.
            field("settled", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field(
                "state",
                W::Struct,
                &[],
                "ProductRunSnapshot | ProductRunSettlementSnapshot",
                "ProductRunSnapshot | ProductRunSettlementSnapshot",
                J::OneOfRef(&["ProductRunSnapshot", "ProductRunSettlementSnapshot"]),
                true,
            ),
            field(
                "mode",
                W::U16,
                &[],
                "ProductInteractionMode",
                "\"chat\" | \"plan\" | \"review\" | \"build\"",
                J::Enum(&["chat", "plan", "review", "build"]),
                true,
            ),
            field(
                "models",
                W::Struct,
                &[],
                "ProductRoleModels",
                "ProductRoleModels",
                J::Ref("ProductRoleModels"),
                true,
            ),
            field("received", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("incorporated", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field(
                "activities",
                W::Sequence,
                &[B::ProductActivities, B::SortedUnique],
                "Vec<ProductActivity>",
                "readonly ProductActivity[]",
                J::ArrayRef("ProductActivity"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductModelQuery",
        rust_type: "ProductModelQuery",
        fields: &[
            field(
                "profile",
                W::Identifier,
                &[B::NonZero],
                "ProviderProfileId",
                "ProviderProfileId",
                J::Identifier,
                true,
            ),
            field("refresh", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
        ],
    },
    AppTypeDescriptor {
        name: "ProductModelInfo",
        rust_type: "ProductModelInfo",
        fields: &[
            field("id", W::Utf8, &[B::ProductModelBytes], "String", "string", J::String, true),
            field("label", W::Utf8, &[B::ProductModelBytes], "String", "string", J::String, true),
            field("tools", W::Option, &[], "Option<bool>", "boolean", J::Boolean, false),
        ],
    },
    AppTypeDescriptor {
        name: "ProductModelCatalog",
        rust_type: "ProductModelCatalog",
        fields: &[
            field(
                "profile",
                W::Identifier,
                &[B::NonZero],
                "ProviderProfileId",
                "ProviderProfileId",
                J::Identifier,
                true,
            ),
            field(
                "configured",
                W::Utf8,
                &[B::ProductModelBytes],
                "String",
                "string",
                J::String,
                true,
            ),
            field("fetchedUnixSeconds", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field("cached", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field("error", W::Utf8, &[B::DiagnosticBytes], "String", "string", J::String, true),
            field(
                "models",
                W::Sequence,
                &[B::ProductModels],
                "Vec<ProductModelInfo>",
                "readonly ProductModelInfo[]",
                J::ArrayRef("ProductModelInfo"),
                true,
            ),
        ],
    },
];
