//! Conversation-library, public source snippet, and fork-lineage metadata.

use super::super::{
    AppFieldDescriptor, AppTypeDescriptor, CanonicalWireType as W, FieldBound as B, JsonShape as J,
    field,
};

const fn query(name: &'static str) -> AppFieldDescriptor {
    field(name, W::Struct, &[], "WorkbenchQuery", "WorkbenchQuery", J::Ref("WorkbenchQuery"), true)
}
const fn revision(name: &'static str) -> AppFieldDescriptor {
    field(name, W::U64, &[], "u64", "UInt64", J::U64String, true)
}
const fn optional_budget() -> AppFieldDescriptor {
    field(
        "allocation",
        W::Option,
        &[],
        "Option<WorkbenchForkBudget>",
        "WorkbenchForkBudget",
        J::Ref("WorkbenchForkBudget"),
        false,
    )
}

pub(super) const LIBRARY_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "ConversationLibraryQuery",
        rust_type: "ConversationLibraryQuery",
        fields: &[
            field(
                "workspace",
                W::Identifier,
                &[B::NonZero],
                "WorkspaceId",
                "WorkspaceId",
                J::Identifier,
                true,
            ),
            field(
                "literal",
                W::Option,
                &[B::ConversationSearchBytes],
                "Option<ConversationSearchText>",
                "string",
                J::String,
                false,
            ),
            field("includeArchived", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field("offset", W::U32, &[], "u32", "number", J::U32, true),
            field(
                "limit",
                W::U16,
                &[B::NonZero, B::ConversationLibraryPage],
                "u16",
                "number",
                J::U16,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchForkBudget",
        rust_type: "WorkbenchForkBudget",
        fields: &[
            field("activeMillis", W::U64, &[B::NonZero], "u64", "UInt64", J::U64String, true),
            field("requests", W::U32, &[B::NonZero], "u32", "number", J::U32, true),
            field("toolCalls", W::U32, &[B::NonZero], "u32", "number", J::U32, true),
            field("totalTokens", W::U64, &[B::NonZero], "u64", "UInt64", J::U64String, true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchForkRequest",
        rust_type: "WorkbenchForkRequest",
        fields: &[
            query("child"),
            field(
                "title",
                W::Utf8,
                &[B::ConversationTitleBytes],
                "ConversationTitle",
                "string",
                J::String,
                true,
            ),
            field(
                "checkpoint",
                W::Identifier,
                &[B::NonZero],
                "ControlOperationId",
                "ControlOperationId",
                J::Identifier,
                true,
            ),
            revision("sourceRevision"),
            revision("contextGeneration"),
            revision("briefRevision"),
            revision("goalRevision"),
            field(
                "mode",
                W::U16,
                &[],
                "WorkbenchForkMode",
                "\"readOnlyCurrentWorkspace\" | \"isolatedWritableWorkspace\"",
                J::Enum(&["readOnlyCurrentWorkspace", "isolatedWritableWorkspace"]),
                true,
            ),
            optional_budget(),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchForkIntent",
        rust_type: "WorkbenchIntent",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "WorkbenchIntent",
                "\"forkConversation\"",
                J::Enum(&["forkConversation"]),
                true,
            ),
            field(
                "fork",
                W::Struct,
                &[],
                "WorkbenchForkRequest",
                "WorkbenchForkRequest",
                J::Ref("WorkbenchForkRequest"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ConversationInputSource",
        rust_type: "ConversationMessageSource",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "ConversationMessageSource",
                "\"input\"",
                J::Enum(&["input"]),
                true,
            ),
            field(
                "conversation",
                W::Identifier,
                &[B::NonZero],
                "ConversationId",
                "ConversationId",
                J::Identifier,
                true,
            ),
            field(
                "input",
                W::Identifier,
                &[B::NonZero],
                "WorkbenchInputId",
                "WorkbenchInputId",
                J::Identifier,
                true,
            ),
            revision("revision"),
        ],
    },
    AppTypeDescriptor {
        name: "ConversationReplySource",
        rust_type: "ConversationMessageSource",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "ConversationMessageSource",
                "\"reply\"",
                J::Enum(&["reply"]),
                true,
            ),
            field(
                "conversation",
                W::Identifier,
                &[B::NonZero],
                "ConversationId",
                "ConversationId",
                J::Identifier,
                true,
            ),
            field(
                "operation",
                W::Identifier,
                &[B::NonZero],
                "ControlOperationId",
                "ControlOperationId",
                J::Identifier,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ConversationLegacySource",
        rust_type: "ConversationMessageSource",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "ConversationMessageSource",
                "\"legacy\"",
                J::Enum(&["legacy"]),
                true,
            ),
            field("run", W::Identifier, &[B::NonZero], "RunId", "RunId", J::Identifier, true),
            field("index", W::U32, &[], "u32", "number", J::U32, true),
        ],
    },
    AppTypeDescriptor {
        name: "ConversationSearchSnippet",
        rust_type: "ConversationSearchSnippet",
        fields: &[
            field(
                "source",
                W::Struct,
                &[],
                "ConversationMessageSource",
                "ConversationInputSource | ConversationReplySource | ConversationLegacySource",
                J::OneOfRef(&[
                    "ConversationInputSource",
                    "ConversationReplySource",
                    "ConversationLegacySource",
                ]),
                true,
            ),
            field(
                "text",
                W::Utf8,
                &[B::ConversationSnippetBytes],
                "String",
                "string",
                J::String,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchBranchLineage",
        rust_type: "WorkbenchBranchLineage",
        fields: &[
            query("parent"),
            field(
                "checkpoint",
                W::Identifier,
                &[B::NonZero],
                "ControlOperationId",
                "ControlOperationId",
                J::Identifier,
                true,
            ),
            revision("sourceRevision"),
            revision("contextGeneration"),
            revision("briefRevision"),
            revision("goalRevision"),
            field(
                "mode",
                W::U16,
                &[],
                "WorkbenchForkMode",
                "\"readOnlyCurrentWorkspace\" | \"isolatedWritableWorkspace\"",
                J::Enum(&["readOnlyCurrentWorkspace", "isolatedWritableWorkspace"]),
                true,
            ),
            optional_budget(),
        ],
    },
    AppTypeDescriptor {
        name: "ConversationLibraryItem",
        rust_type: "ConversationLibraryItem",
        fields: &[
            query("query"),
            field(
                "title",
                W::Utf8,
                &[B::ConversationTitleBytes],
                "ConversationTitle",
                "string",
                J::String,
                true,
            ),
            field("pinned", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field("archived", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field("activityRevision", W::U64, &[B::NonZero], "u64", "UInt64", J::U64String, true),
            field(
                "legacyRun",
                W::Option,
                &[B::NonZero],
                "Option<RunId>",
                "RunId",
                J::Identifier,
                false,
            ),
            field(
                "goalState",
                W::Option,
                &[],
                "Option<WorkbenchGoalState>",
                "\"active\" | \"waitingForUser\" | \"pausing\" | \"paused\" | \"blocked\" | \"budgetReached\" | \"achieved\" | \"cancelled\"",
                J::Enum(&[
                    "active",
                    "waitingForUser",
                    "pausing",
                    "paused",
                    "blocked",
                    "budgetReached",
                    "achieved",
                    "cancelled",
                ]),
                false,
            ),
            field("goalDraft", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field(
                "handoff",
                W::Utf8,
                &[B::ConversationHandoffBytes],
                "String",
                "string",
                J::String,
                true,
            ),
            field(
                "snippet",
                W::Option,
                &[],
                "Option<ConversationSearchSnippet>",
                "ConversationSearchSnippet",
                J::Ref("ConversationSearchSnippet"),
                false,
            ),
            field(
                "branch",
                W::Option,
                &[],
                "Option<WorkbenchBranchLineage>",
                "WorkbenchBranchLineage",
                J::Ref("WorkbenchBranchLineage"),
                false,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ConversationLibraryPage",
        rust_type: "ConversationLibraryPage",
        fields: &[
            field(
                "query",
                W::Struct,
                &[],
                "ConversationLibraryQuery",
                "ConversationLibraryQuery",
                J::Ref("ConversationLibraryQuery"),
                true,
            ),
            field("total", W::U32, &[], "u32", "number", J::U32, true),
            field("nextOffset", W::Option, &[], "Option<u32>", "number", J::U32, false),
            field(
                "items",
                W::Sequence,
                &[B::ConversationLibraryPage],
                "Vec<ConversationLibraryItem>",
                "readonly ConversationLibraryItem[]",
                J::ArrayRef("ConversationLibraryItem"),
                true,
            ),
        ],
    },
];
