//! Product-run snapshot metadata.

use super::super::{
    AppTypeDescriptor, CanonicalWireType as W, FieldBound as B, JsonShape as J, field,
};

mod settlement;

pub(super) use settlement::SETTLEMENT_TYPES;

pub(super) const PRODUCT_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "ProductProviderSelection",
        rust_type: "ProductProviderSelection",
        fields: &[
            field(
                "writer",
                W::Identifier,
                &[B::NonZero],
                "ProviderProfileId",
                "ProviderProfileId",
                J::Identifier,
                true,
            ),
            field(
                "reviewer",
                W::Identifier,
                &[B::NonZero],
                "ProviderProfileId",
                "ProviderProfileId",
                J::Identifier,
                true,
            ),
            field(
                "fixer",
                W::Identifier,
                &[B::NonZero],
                "ProviderProfileId",
                "ProviderProfileId",
                J::Identifier,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ProductDeliverable",
        rust_type: "ProductDeliverable",
        fields: &[
            field(
                "workspacePath",
                W::Utf8,
                &[B::ProductDetailBytes],
                "String",
                "string",
                J::String,
                true,
            ),
            field(
                "changedPaths",
                W::Sequence,
                &[B::ProductDeliverablePaths, B::ProductDetailBytes],
                "Vec<String>",
                "readonly string[]",
                J::StringArray,
                true,
            ),
            field(
                "successfulCommands",
                W::Sequence,
                &[B::ProductDeliverableCommands, B::ProductDetailBytes],
                "Vec<String>",
                "readonly string[]",
                J::StringArray,
                true,
            ),
            field(
                "runInstructions",
                W::Utf8,
                &[B::ProductDetailBytes],
                "String",
                "string",
                J::String,
                true,
            ),
            field("accepted", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field(
                "commitRevision",
                W::Utf8,
                &[B::ProductDetailBytes],
                "String",
                "string",
                J::String,
                true,
            ),
            field(
                "exportPath",
                W::Utf8,
                &[B::ProductDetailBytes],
                "String",
                "string",
                J::String,
                true,
            ),
            field("discarded", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
        ],
    },
    AppTypeDescriptor {
        name: "ProductRunSnapshot",
        rust_type: "ProductRunSnapshot",
        fields: &[
            field("runId", W::Identifier, &[B::NonZero], "RunId", "RunId", J::Identifier, true),
            field(
                "workspaceId",
                W::Identifier,
                &[B::NonZero],
                "WorkspaceId",
                "WorkspaceId",
                J::Identifier,
                true,
            ),
            field(
                "providers",
                W::Struct,
                &[],
                "ProductProviderSelection",
                "ProductProviderSelection",
                J::Ref("ProductProviderSelection"),
                true,
            ),
            field(
                "phase",
                W::U16,
                &[],
                "ProductRunPhase",
                "ProductRunPhase",
                J::Enum(&[
                    "queued",
                    "writing",
                    "checking",
                    "reviewing",
                    "fixing",
                    "verifying",
                    "complete",
                    "failed",
                    "cancelled",
                    "recovery-required",
                    "waiting-for-user",
                    "designing",
                ]),
                true,
            ),
            field("cycle", W::U32, &[], "u32", "number", J::U32, true),
            field("task", W::Utf8, &[B::ProductTaskBytes], "String", "string", J::String, true),
            field("status", W::Utf8, &[B::ProductDetailBytes], "String", "string", J::String, true),
            field("diff", W::Utf8, &[B::ProductDetailBytes], "String", "string", J::String, true),
            field("gates", W::Utf8, &[B::ProductDetailBytes], "String", "string", J::String, true),
            field("review", W::Utf8, &[B::ProductDetailBytes], "String", "string", J::String, true),
            field(
                "summary",
                W::Utf8,
                &[B::ProductDetailBytes],
                "String",
                "string",
                J::String,
                true,
            ),
            field(
                "deliverable",
                W::Option,
                &[],
                "Option<ProductDeliverable>",
                "ProductDeliverable",
                J::Ref("ProductDeliverable"),
                false,
            ),
        ],
    },
];
