//! Prompt-answer and terminal flow field metadata.

use super::super::{AppTypeDescriptor, CanonicalWireType, FieldBound as B, JsonShape as J, field};

pub(super) const PROMPT_TERMINAL_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "PromptBinding",
        rust_type: "PromptBinding",
        fields: &[
            field(
                "kind",
                CanonicalWireType::U8,
                &[],
                "PromptKind",
                "\"approval\" | \"user-input\"",
                J::Enum(&["approval", "user-input"]),
                true,
            ),
            field(
                "correlation",
                CanonicalWireType::Struct,
                &[],
                "PromptCorrelation",
                "PromptCorrelation",
                J::Ref("PromptCorrelation"),
                true,
            ),
            field(
                "choices",
                CanonicalWireType::Sequence,
                &[B::PromptChoices],
                "Vec<PromptChoice>",
                "readonly PromptChoice[]",
                J::ArrayRef("PromptChoice"),
                true,
            ),
            field(
                "constraints",
                CanonicalWireType::Sequence,
                &[B::CodecCollectionItems],
                "Vec<PromptConstraint>",
                "readonly PromptConstraint[]",
                J::ArrayRef("PromptConstraint"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "PromptAnswer",
        rust_type: "PromptAnswer",
        fields: &[
            field(
                "correlation",
                CanonicalWireType::Struct,
                &[],
                "PromptCorrelation",
                "PromptCorrelation",
                J::Ref("PromptCorrelation"),
                true,
            ),
            field(
                "answerKind",
                CanonicalWireType::U8,
                &[],
                "PromptAnswerPayload",
                "\"approval\" | \"user-input\"",
                J::Enum(&["approval", "user-input"]),
                true,
            ),
            field(
                "approvalIntent",
                CanonicalWireType::U8,
                &[],
                "Option<ApprovalIntent>",
                "\"approve\" | \"deny\" | \"cancel\"",
                J::Enum(&["approve", "deny", "cancel"]),
                false,
            ),
            field(
                "rationale",
                CanonicalWireType::Option,
                &[B::CodecStringBytes],
                "Option<String>",
                "string",
                J::String,
                false,
            ),
            field(
                "inputKind",
                CanonicalWireType::U8,
                &[],
                "Option<UserInputValue>",
                "\"text\" | \"selection\" | \"confirmation\" | \"secret-reference\"",
                J::Enum(&["text", "selection", "confirmation", "secret-reference"]),
                false,
            ),
            field(
                "textValue",
                CanonicalWireType::Utf8,
                &[B::CodecStringBytes],
                "Option<String>",
                "string",
                J::String,
                false,
            ),
            field(
                "confirmationValue",
                CanonicalWireType::Boolean,
                &[],
                "Option<bool>",
                "boolean",
                J::Boolean,
                false,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "PromptCancellation",
        rust_type: "PromptCancellation",
        fields: &[
            field(
                "correlation",
                CanonicalWireType::Struct,
                &[],
                "PromptCorrelation",
                "PromptCorrelation",
                J::Ref("PromptCorrelation"),
                true,
            ),
            field(
                "correlationId",
                CanonicalWireType::Identifier,
                &[B::NonZero, B::EnvelopeBinding],
                "CorrelationId",
                "CorrelationId",
                J::Identifier,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "TerminalBinding",
        rust_type: "TerminalBinding",
        fields: &[
            field(
                "attachmentId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "TerminalAttachmentId",
                "TerminalAttachmentId",
                J::Identifier,
                true,
            ),
            field(
                "processId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "ProcessId",
                "ProcessId",
                J::Identifier,
                true,
            ),
            field(
                "originatingRequestId",
                CanonicalWireType::Identifier,
                &[B::NonZero, B::EnvelopeBinding],
                "RequestId",
                "RequestId",
                J::Identifier,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "TerminalInput",
        rust_type: "TerminalInput",
        fields: &[
            field(
                "binding",
                CanonicalWireType::Struct,
                &[],
                "TerminalBinding",
                "TerminalBinding",
                J::Ref("TerminalBinding"),
                true,
            ),
            field(
                "bytes",
                CanonicalWireType::Bytes,
                &[B::TerminalChunkBytes],
                "Vec<u8>",
                "Base64Bytes",
                J::Base64,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "TerminalResize",
        rust_type: "TerminalResize",
        fields: &[
            field(
                "binding",
                CanonicalWireType::Struct,
                &[],
                "TerminalBinding",
                "TerminalBinding",
                J::Ref("TerminalBinding"),
                true,
            ),
            field("columns", CanonicalWireType::U16, &[B::NonZero], "u16", "number", J::U16, true),
            field("rows", CanonicalWireType::U16, &[B::NonZero], "u16", "number", J::U16, true),
        ],
    },
    AppTypeDescriptor {
        name: "TerminalDetach",
        rust_type: "TerminalDetach",
        fields: &[
            field(
                "binding",
                CanonicalWireType::Struct,
                &[],
                "TerminalBinding",
                "TerminalBinding",
                J::Ref("TerminalBinding"),
                true,
            ),
            field(
                "correlationId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "CorrelationId",
                "CorrelationId",
                J::Identifier,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "TerminalCancellation",
        rust_type: "TerminalCancellation",
        fields: &[
            field(
                "binding",
                CanonicalWireType::Struct,
                &[],
                "TerminalBinding",
                "TerminalBinding",
                J::Ref("TerminalBinding"),
                true,
            ),
            field(
                "correlationId",
                CanonicalWireType::Identifier,
                &[B::NonZero, B::EnvelopeBinding],
                "CorrelationId",
                "CorrelationId",
                J::Identifier,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "TerminalOutput",
        rust_type: "TerminalOutput",
        fields: &[
            field(
                "binding",
                CanonicalWireType::Struct,
                &[],
                "TerminalBinding",
                "TerminalBinding",
                J::Ref("TerminalBinding"),
                true,
            ),
            field(
                "sequence",
                CanonicalWireType::U64,
                &[B::Contiguous],
                "u64",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "offset",
                CanonicalWireType::U64,
                &[B::Contiguous],
                "u64",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "stream",
                CanonicalWireType::U8,
                &[],
                "TerminalStream",
                "\"stdout\" | \"stderr\"",
                J::Enum(&["stdout", "stderr"]),
                true,
            ),
            field(
                "bytes",
                CanonicalWireType::Bytes,
                &[B::TerminalChunkBytes],
                "Vec<u8>",
                "Base64Bytes",
                J::Base64,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "TerminalExit",
        rust_type: "TerminalExit",
        fields: &[
            field(
                "binding",
                CanonicalWireType::Struct,
                &[],
                "TerminalBinding",
                "TerminalBinding",
                J::Ref("TerminalBinding"),
                true,
            ),
            field(
                "nextSequence",
                CanonicalWireType::U64,
                &[B::Contiguous],
                "u64",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "finalOffset",
                CanonicalWireType::U64,
                &[B::Contiguous],
                "u64",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "disposition",
                CanonicalWireType::U8,
                &[],
                "TerminalExitDisposition",
                "TerminalExitDisposition",
                J::Ref("TerminalExitDisposition"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "TerminalExitDisposition",
        rust_type: "TerminalExitDisposition",
        fields: &[
            field(
                "kind",
                CanonicalWireType::U8,
                &[],
                "TerminalExitDisposition",
                "\"code\" | \"signal\" | \"unknown\"",
                J::Enum(&["code", "signal", "unknown"]),
                true,
            ),
            field("value", CanonicalWireType::I32, &[], "Option<i32>", "number", J::I32, false),
        ],
    },
];
