//! Revisioned control projections in exact canonical field order.

use super::super::{
    AppTypeDescriptor, CanonicalWireType as W, FieldBound as B, JsonShape as J, field,
};

pub(super) const WORKBENCH_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "WorkbenchContinuation",
        rust_type: "WorkbenchContinuation",
        fields: &[
            field(
                "query",
                W::Struct,
                &[],
                "WorkbenchQuery",
                "WorkbenchQuery",
                J::Ref("WorkbenchQuery"),
                true,
            ),
            field(
                "mode",
                W::U16,
                &[],
                "ProductInteractionMode",
                "\"chat\" | \"plan\" | \"review\" | \"build\"",
                J::Enum(&["chat", "plan", "review", "build"]),
                true,
            ),
            field(
                "operation",
                W::Option,
                &[B::NonZero],
                "Option<ControlOperationId>",
                "ControlOperationId",
                J::Identifier,
                false,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchExecutionState",
        rust_type: "WorkbenchExecutionState",
        fields: &[
            field(
                "snapshot",
                W::Struct,
                &[],
                "WorkbenchSnapshot",
                "WorkbenchSnapshot",
                J::Ref("WorkbenchSnapshot"),
                true,
            ),
            field("run", W::Option, &[B::NonZero], "Option<RunId>", "RunId", J::Identifier, false),
            field("goal", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchExecutionSettings",
        rust_type: "WorkbenchExecutionSettings",
        fields: &[
            field("run", W::Identifier, &[B::NonZero], "RunId", "RunId", J::Identifier, true),
            field(
                "providers",
                W::Struct,
                &[],
                "ProductProviderSelection",
                "ProductProviderSelection",
                J::Ref("ProductProviderSelection"),
                true,
            ),
            field(
                "mode",
                W::U16,
                &[],
                "ProductInteractionMode",
                "\"chat\" | \"plan\" | \"review\" | \"build\"",
                J::Enum(&["chat", "plan", "review", "build"]),
                true,
            ),
            field("hasEffort", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field(
                "models",
                W::Struct,
                &[],
                "ProductRoleModels",
                "ProductRoleModels",
                J::Ref("ProductRoleModels"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchStartIntent",
        rust_type: "WorkbenchIntent",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "WorkbenchIntent",
                "\"startExecution\"",
                J::Enum(&["startExecution"]),
                true,
            ),
            field(
                "settings",
                W::Struct,
                &[],
                "WorkbenchExecutionSettings",
                "WorkbenchExecutionSettings",
                J::Ref("WorkbenchExecutionSettings"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchQuery",
        rust_type: "WorkbenchQuery",
        fields: &[
            field(
                "conversation",
                W::Identifier,
                &[B::NonZero],
                "ConversationId",
                "ConversationId",
                J::Identifier,
                true,
            ),
            field(
                "workspace",
                W::Identifier,
                &[B::NonZero],
                "WorkspaceId",
                "WorkspaceId",
                J::Identifier,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchTitleIntent",
        rust_type: "WorkbenchIntent",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "WorkbenchIntent",
                "\"createConversation\" | \"renameConversation\"",
                J::Enum(&["createConversation", "renameConversation"]),
                true,
            ),
            field(
                "title",
                W::Utf8,
                &[B::ConversationTitleBytes],
                "ConversationTitle",
                "string",
                J::String,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchFlagIntent",
        rust_type: "WorkbenchIntent",
        fields: &[
            field(
                "kind",
                W::U16,
                &[],
                "WorkbenchIntent",
                "\"pinConversation\" | \"archiveConversation\"",
                J::Enum(&["pinConversation", "archiveConversation"]),
                true,
            ),
            field("value", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchCommand",
        rust_type: "WorkbenchCommand",
        fields: &[
            field(
                "operation",
                W::Identifier,
                &[B::NonZero],
                "ControlOperationId",
                "ControlOperationId",
                J::Identifier,
                true,
            ),
            field(
                "query",
                W::Struct,
                &[],
                "WorkbenchQuery",
                "WorkbenchQuery",
                J::Ref("WorkbenchQuery"),
                true,
            ),
            field("expectedRevision", W::U64, &[], "u64", "UInt64", J::U64String, true),
            field(
                "intent",
                W::Struct,
                &[],
                "WorkbenchIntent",
                "WorkbenchTitleIntent | WorkbenchFlagIntent | WorkbenchForkIntent | WorkbenchQueueControlIntent | WorkbenchStartIntent | WorkbenchBriefIntent | WorkbenchBriefAcceptIntent | WorkbenchSetContextIntent | WorkbenchCreateCheckpointIntent | WorkbenchApplyRewindIntent | WorkbenchApplyCompactionIntent | WorkbenchAttachImageIntent | WorkbenchSelectImageIntent | WorkbenchAttachFileIntent | WorkbenchAttachFileImportIntent | WorkbenchEnqueueMessageIntent | WorkbenchEnqueueMessageBundleIntent | WorkbenchSelectFileIntent | WorkbenchStartGoalIntent | WorkbenchPauseGoalIntent | WorkbenchResumeOrClearGoalIntent | WorkbenchAddReviewIntent | WorkbenchRebindReviewIntent | WorkbenchDismissReviewIntent | WorkbenchStartPreviewIntent | WorkbenchInteractPreviewIntent | WorkbenchCapturePreviewIntent | WorkbenchStopPreviewIntent | WorkbenchCheckPreviewIntent | WorkbenchArtifactFeedbackIntent | WorkbenchPermissionIntent | WorkbenchSaveGuidanceIntent | WorkbenchReviseGuidanceIntent | WorkbenchPinGuidanceIntent | WorkbenchScopeGuidanceIntent | WorkbenchForgetGuidanceIntent | WorkbenchInitApplyIntent | WorkbenchInitArtifactIntent",
                J::OneOfRef(&[
                    "WorkbenchTitleIntent",
                    "WorkbenchFlagIntent",
                    "WorkbenchForkIntent",
                    "WorkbenchQueueControlIntent",
                    "WorkbenchStartIntent",
                    "WorkbenchBriefIntent",
                    "WorkbenchBriefAcceptIntent",
                    "WorkbenchSetContextIntent",
                    "WorkbenchCreateCheckpointIntent",
                    "WorkbenchApplyRewindIntent",
                    "WorkbenchApplyCompactionIntent",
                    "WorkbenchAttachImageIntent",
                    "WorkbenchSelectImageIntent",
                    "WorkbenchAttachFileIntent",
                    "WorkbenchAttachFileImportIntent",
                    "WorkbenchEnqueueMessageIntent",
                    "WorkbenchEnqueueMessageBundleIntent",
                    "WorkbenchSelectFileIntent",
                    "WorkbenchStartGoalIntent",
                    "WorkbenchPauseGoalIntent",
                    "WorkbenchResumeOrClearGoalIntent",
                    "WorkbenchAddReviewIntent",
                    "WorkbenchRebindReviewIntent",
                    "WorkbenchDismissReviewIntent",
                    "WorkbenchStartPreviewIntent",
                    "WorkbenchInteractPreviewIntent",
                    "WorkbenchCapturePreviewIntent",
                    "WorkbenchStopPreviewIntent",
                    "WorkbenchCheckPreviewIntent",
                    "WorkbenchArtifactFeedbackIntent",
                    "WorkbenchPermissionIntent",
                    "WorkbenchSaveGuidanceIntent",
                    "WorkbenchReviseGuidanceIntent",
                    "WorkbenchPinGuidanceIntent",
                    "WorkbenchScopeGuidanceIntent",
                    "WorkbenchForgetGuidanceIntent",
                    "WorkbenchInitApplyIntent",
                    "WorkbenchInitArtifactIntent",
                ]),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchSnapshot",
        rust_type: "WorkbenchSnapshot",
        fields: &[
            field(
                "query",
                W::Struct,
                &[],
                "WorkbenchQuery",
                "WorkbenchQuery",
                J::Ref("WorkbenchQuery"),
                true,
            ),
            field("revision", W::U64, &[B::NonZero], "u64", "UInt64", J::U64String, true),
            field(
                "title",
                W::Utf8,
                &[B::ConversationTitleBytes],
                "ConversationTitle",
                "string",
                J::String,
                true,
            ),
            field("pinned", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
            field("archived", W::Boolean, &[], "bool", "boolean", J::Boolean, true),
        ],
    },
    AppTypeDescriptor {
        name: "WorkbenchReceipt",
        rust_type: "WorkbenchReceipt",
        fields: &[
            field(
                "operation",
                W::Identifier,
                &[B::NonZero],
                "ControlOperationId",
                "ControlOperationId",
                J::Identifier,
                true,
            ),
            field(
                "query",
                W::Struct,
                &[],
                "WorkbenchQuery",
                "WorkbenchQuery",
                J::Ref("WorkbenchQuery"),
                true,
            ),
            field("acceptedRevision", W::U64, &[B::NonZero], "u64", "UInt64", J::U64String, true),
            field("payloadDigest", W::Digest, &[], "Sha256Digest", "Sha256Digest", J::Digest, true),
        ],
    },
];
