//! Compatibility against immutable histories generated by the protected-base reducer.

use std::path::PathBuf;

use peritus_codec::CodecLimits;
use peritus_scheduler::{
    SchedulerBinding, SchedulerCommand, SchedulerCommandKind, SchedulerErrorKind,
    SchedulerSemantics, WorkPhase, decide, decode_scheduler_command, decode_scheduler_event,
    decode_scheduler_state, encode_scheduler_command, encode_scheduler_event,
    encode_scheduler_state, replay, start,
};
use peritus_types::{CommandId, EventId};

fn frame(scenario: &str, name: &str) -> Vec<u8> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../fixtures/protocol/scheduler-v1-recovery");
    std::fs::read(root.join(scenario).join(name)).expect("immutable protected-base frame exists")
}

#[test]
fn old_benign_history_requires_legacy_admission_while_new_aggregates_reserve_recovery() {
    let bytes = frame("benign", "command-01.bin");
    let historical = decode_scheduler_command(&bytes, CodecLimits::PRODUCTION)
        .expect("fixed historical genesis command");
    let old = start(&historical).expect("historical genesis reduces");
    let binding = old.state().binding();
    let current_binding = SchedulerBinding::new(
        binding.run_id(),
        binding.scheduler_id(),
        binding.revision(),
        binding.limits(),
        binding.capacity().clone(),
    )
    .expect("same independent limits and capacity");
    assert_ne!(current_binding.digest(), binding.digest(), "semantic identity binds the digest");
    let genesis = SchedulerCommand::new(
        historical.command_id(),
        historical.event_id(),
        historical.run_id(),
        0,
        None,
        historical.prior_state_digest(),
        historical.revision(),
        SchedulerCommandKind::StartScheduler { binding: current_binding },
    )
    .expect("current-schema genesis");
    let mut state = start(&genesis).expect("current genesis reduces").into_state();
    assert_ne!(state.state_digest(), old.state().state_digest());
    for identity in [3, 4, 5, 6, 7] {
        let bytes = frame("benign", &format!("command-{identity:02}.bin"));
        let legacy = decode_scheduler_command(&bytes, CodecLimits::PRODUCTION)
            .expect("fixed historical command");
        let command = SchedulerCommand::from_state(
            &state,
            legacy.command_id(),
            legacy.event_id(),
            legacy.kind().clone(),
        )
        .expect("current-schema continuation");
        if identity == 7 {
            let previous = state.clone();
            assert_eq!(
                decide(&state, &command).expect_err("recoverable A still consumes pressure").kind(),
                SchedulerErrorKind::LimitExceeded
            );
            assert_eq!(state, previous);
        } else {
            state = decide(&state, &command).expect("same pre-admission behavior").into_state();
        }
    }
}

#[test]
fn historical_admission_and_recovery_replay_with_exact_bytes_and_remain_writable() {
    for scenario in ["benign", "retry", "loss"] {
        let mut events = Vec::new();
        let mut current = None;
        for identity in [1, 3, 4, 5, 6, 7, 8] {
            let command_bytes = frame(scenario, &format!("command-{identity:02}.bin"));
            let event_bytes = frame(scenario, &format!("event-{identity:02}.bin"));
            let command = decode_scheduler_command(&command_bytes, CodecLimits::PRODUCTION)
                .expect("old command decodes");
            let event = decode_scheduler_event(&event_bytes, CodecLimits::PRODUCTION)
                .expect("old event decodes");
            assert_eq!(command.semantics(), SchedulerSemantics::LegacyQueueV1);
            assert_eq!(event.semantics(), SchedulerSemantics::LegacyQueueV1);
            assert_eq!(
                encode_scheduler_command(&command, CodecLimits::PRODUCTION)
                    .expect("old command encodes"),
                command_bytes
            );
            assert_eq!(
                encode_scheduler_event(&event, CodecLimits::PRODUCTION).expect("old event encodes"),
                event_bytes
            );
            let transition = current
                .as_ref()
                .map_or_else(|| start(&command), |state| decide(state, &command))
                .expect("every protected-base admission decision is preserved");
            assert_eq!(transition.event(), &event);
            current = Some(transition.into_state());
            events.push(event);
        }
        let bytes = frame(scenario, "checkpoint.bin");
        let checkpoint = decode_scheduler_state(&bytes, CodecLimits::PRODUCTION)
            .expect("all reachable legacy recovery states decode");
        assert_eq!(
            encode_scheduler_state(&checkpoint, CodecLimits::PRODUCTION)
                .expect("historical checkpoint encodes"),
            bytes
        );
        assert_eq!(current.as_ref(), Some(&checkpoint));
        assert_eq!(replay(&events).expect("historical journal replays"), checkpoint);
        let waiting = checkpoint
            .work()
            .iter()
            .filter(|work| {
                matches!(
                    work.phase(),
                    WorkPhase::Queued | WorkPhase::WaitingDependencies | WorkPhase::RetryPending
                )
            })
            .count();
        assert_eq!(waiting, if scenario == "benign" { 1 } else { 2 });
        let continuation = SchedulerCommand::from_state(
            &checkpoint,
            CommandId::new([80; 16]).expect("nonzero identity"),
            EventId::new([81; 16]).expect("nonzero identity"),
            SchedulerCommandKind::PauseScheduler,
        )
        .expect("legacy aggregate accepts a state-derived continuation");
        let transition =
            decide(&checkpoint, &continuation).expect("legacy scheduler remains writable");
        assert_eq!(continuation.semantics(), SchedulerSemantics::LegacyQueueV1);
        assert_eq!(transition.event().semantics(), SchedulerSemantics::LegacyQueueV1);
        let next = encode_scheduler_state(transition.state(), CodecLimits::PRODUCTION)
            .expect("legacy continuation encodes");
        assert_eq!(
            decode_scheduler_state(&next, CodecLimits::PRODUCTION)
                .expect("legacy continuation decodes"),
            *transition.state()
        );
    }
}
