//! Explicit command catalog entries, with no source-generating macros.

use super::{Arguments, Command, CommandSpec};

pub(super) const COMMANDS: &[CommandSpec] = &[
    CommandSpec {
        command: Command::Chat,
        name: "/chat",
        description: "Talk or request scoped work",
        arguments: Arguments::Message,
    },
    CommandSpec {
        command: Command::Plan,
        name: "/plan",
        description: "Read-only planning",
        arguments: Arguments::Message,
    },
    CommandSpec {
        command: Command::Review,
        name: "/review",
        description: "Fresh independent read-only review",
        arguments: Arguments::Message,
    },
    CommandSpec {
        command: Command::Build,
        name: "/build",
        description: "Checked writer / reviewer / fixer delivery",
        arguments: Arguments::Message,
    },
    CommandSpec {
        command: Command::Model,
        name: "/model",
        description: "Discover and select provider models",
        arguments: Arguments::Model,
    },
    CommandSpec {
        command: Command::Effort,
        name: "/effort",
        description: "Select reasoning effort for chat/writer, reviewer, or fixer",
        arguments: Arguments::Effort,
    },
    CommandSpec {
        command: Command::New,
        name: "/new",
        description: "New conversation; preserve existing work",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Status,
        name: "/status",
        description: "Current conversation and input status",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Diff,
        name: "/diff",
        description: "Inspect retained workspace changes",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Runs,
        name: "/runs",
        description: "Browse runs and handoffs",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Trace,
        name: "/trace",
        description: "Inspect event trace",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Terminal,
        name: "/terminal",
        description: "Attach to a daemon process",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Approvals,
        name: "/approvals",
        description: "Inspect pending approvals",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Details,
        name: "/details",
        description: "Show or hide harness diagnostics",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Stop,
        name: "/stop",
        description: "Stop active work, preserve effects",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Accept,
        name: "/accept",
        description: "Accept the exact candidate",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Commit,
        name: "/commit",
        description: "Commit the exact candidate",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Export,
        name: "/export",
        description: "Export the exact candidate",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Discard,
        name: "/discard",
        description: "Discard the exact candidate",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Run,
        name: "/run",
        description: "Run the retained candidate",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Reconnect,
        name: "/reconnect",
        description: "Reconnect to the daemon",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Doctor,
        name: "/doctor",
        description: "Inspect local readiness; no repairs or network probes",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Sessions,
        name: "/sessions",
        description: "Inspect or edit durable conversation metadata",
        arguments: Arguments::Sessions,
    },
    CommandSpec {
        command: Command::Fork,
        name: "/fork",
        description: "Fork a checkpoint read-only or into an isolated workspace",
        arguments: Arguments::Fork,
    },
    CommandSpec {
        command: Command::Queue,
        name: "/queue",
        description: "Inspect, edit, hold, reorder or withdraw pending instructions",
        arguments: Arguments::Queue,
    },
    CommandSpec {
        command: Command::Context,
        name: "/context",
        description: "Inspect eligible sources or exact sealed request manifests",
        arguments: Arguments::Context,
    },
    CommandSpec {
        command: Command::Compact,
        name: "/compact",
        description: "Preview deterministic local source-handle reduction",
        arguments: Arguments::Compact,
    },
    CommandSpec {
        command: Command::Brief,
        name: "/brief",
        description: "Inspect or revise explicit user-confirmed task fields",
        arguments: Arguments::Brief,
    },
    CommandSpec {
        command: Command::Goal,
        name: "/goal",
        description: "Inspect, draft, and explicitly confirm a persistent goal",
        arguments: Arguments::Goal,
    },
    CommandSpec {
        command: Command::Pause,
        name: "/pause",
        description: "Durably pause goal execution at a named safe boundary",
        arguments: Arguments::Pause,
    },
    CommandSpec {
        command: Command::Resume,
        name: "/resume",
        description: "Explicitly resume the same persistent goal",
        arguments: Arguments::Resume,
    },
    CommandSpec {
        command: Command::Usage,
        name: "/usage",
        description: "Inspect cumulative persistent-goal accounting",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Budget,
        name: "/budget",
        description: "Inspect or replace cumulative persistent-goal limits",
        arguments: Arguments::Budget,
    },
    CommandSpec {
        command: Command::Preview,
        name: "/preview",
        description: "Launch, exercise, capture, and inspect the retained candidate",
        arguments: Arguments::Preview,
    },
    CommandSpec {
        command: Command::Checkpoint,
        name: "/checkpoint",
        description: "Capture or inspect an exact whole-file checkpoint",
        arguments: Arguments::Checkpoint,
    },
    CommandSpec {
        command: Command::Rewind,
        name: "/rewind",
        description: "Preview files, conversation, or combined checkpoint rewind",
        arguments: Arguments::Rewind,
    },
    CommandSpec {
        command: Command::Attach,
        name: "/attach",
        description: "Choose an image, inspect exact bytes and provider, then confirm",
        arguments: Arguments::Attachment,
    },
    CommandSpec {
        command: Command::Files,
        name: "/files",
        description: "Preview a workspace file/range and choose snapshot or refresh",
        arguments: Arguments::Attachment,
    },
    CommandSpec {
        command: Command::Permissions,
        name: "/permissions",
        description: "Inspect or narrow effective workspace capabilities",
        arguments: Arguments::Permissions,
    },
    CommandSpec {
        command: Command::Init,
        name: "/init",
        description: "Discover project controls and review an exact instruction diff",
        arguments: Arguments::Init,
    },
    CommandSpec {
        command: Command::Memory,
        name: "/memory",
        description: "Inspect, save, revise, scope, pin, or forget project guidance",
        arguments: Arguments::Memory,
    },
    CommandSpec {
        command: Command::Help,
        name: "/help",
        description: "Show slash commands",
        arguments: Arguments::None,
    },
    CommandSpec {
        command: Command::Quit,
        name: "/quit",
        description: "Detach client; do not stop daemon work",
        arguments: Arguments::None,
    },
];
