//! Deterministic checked-in artifact renderers.

use super::{FAMILIES, LIFECYCLE_VARIANTS, VariantTag};

/// One generated repository-relative text artifact.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedArtifact {
    /// Path below the selected output root.
    pub path: &'static str,
    /// Complete deterministic UTF-8 content.
    pub content: String,
}

/// Renders every checked-in schema and client declaration.
#[must_use]
pub fn generated_artifacts() -> Vec<GeneratedArtifact> {
    vec![
        GeneratedArtifact {
            path: "protocol/generated/peritus-domain-v1.schema.json",
            content: render_schema_json(),
        },
        GeneratedArtifact {
            path: "protocol/generated/peritus-domain-v1.ts",
            content: render_typescript(),
        },
    ]
}

fn render_schema_json() -> String {
    let mut output = String::from(
        "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"title\": \"Peritus canonical domain protocol v1\",\n  \"type\": \"object\",\n  \"frame\": {\n    \"magicHex\": \"50525453\",\n    \"formatVersion\": 1,\n    \"headerBytes\": 16,\n    \"integerByteOrder\": \"big-endian\",\n    \"lengthType\": \"u32\",\n    \"enumType\": \"u16\",\n    \"booleanTags\": [0, 1],\n    \"optionTags\": [0, 1],\n    \"reservedFlags\": 0\n  },\n  \"authorityRule\": \"Decoded bytes establish syntax and domain validity only; they never grant authority, evidence provenance, or durable commit.\",\n  \"families\": [\n",
    );
    for (index, family) in FAMILIES.iter().enumerate() {
        let comma = if index + 1 == FAMILIES.len() { "" } else { "," };
        output.push_str("    {\"tag\": ");
        output.push_str(&family.tag.to_string());
        output.push_str(", \"name\": \"");
        output.push_str(family.name);
        output.push_str("\", \"schemaVersion\": ");
        output.push_str(&family.schema_version.to_string());
        output.push_str(", \"inertOnly\": ");
        output.push_str(&family.inert_only.to_string());
        output.push('}');
        output.push_str(comma);
        output.push('\n');
    }
    output.push_str("  ],\n  \"variants\": {\n");
    for (set_index, set) in LIFECYCLE_VARIANTS.iter().enumerate() {
        output.push_str("    \"");
        output.push_str(set.name);
        output.push_str("\": [\n");
        for (variant_index, variant) in set.variants.iter().enumerate() {
            push_json_variant(&mut output, variant, variant_index + 1 != set.variants.len());
        }
        output.push_str("    ]");
        if set_index + 1 != LIFECYCLE_VARIANTS.len() {
            output.push(',');
        }
        output.push('\n');
    }
    output.push_str(
        "  },\n  \"primitives\": {\n    \"identifier\": {\"bytes\": 16, \"constraint\": \"not-all-zero\"},\n    \"sha256\": {\"bytes\": 32},\n    \"string\": {\"encoding\": \"utf-8\", \"prefix\": \"u32-byte-length\"},\n    \"opaque\": {\"prefix\": \"u32-byte-length\"},\n    \"collection\": {\"prefix\": \"u32-item-count\"}\n  }\n}\n",
    );
    output
}

fn render_typescript() -> String {
    let mut output = String::from(
        "// @generated by peritus-protocol-codegen; do not edit.\n\nexport const PERITUS_MAGIC = new Uint8Array([0x50, 0x52, 0x54, 0x53]);\nexport const PERITUS_FORMAT_VERSION = 1 as const;\nexport const PERITUS_HEADER_BYTES = 16 as const;\n\nexport type Bytes16 = Uint8Array & { readonly __bytes16: unique symbol };\nexport type Sha256 = Uint8Array & { readonly __sha256: unique symbol };\n\nexport interface FrameHeader {\n  readonly family: MessageFamilyTag;\n  readonly schemaVersion: 1;\n  readonly payloadBytes: number;\n}\n\nexport const MESSAGE_FAMILY = {\n",
    );
    for family in FAMILIES {
        let constant = family.name.replace('-', "_").to_ascii_uppercase();
        output.push_str("  ");
        output.push_str(&constant);
        output.push_str(": ");
        output.push_str(&family.tag.to_string());
        output.push_str(",\n");
    }
    output.push_str("} as const;\n\nexport type MessageFamilyTag = typeof MESSAGE_FAMILY[keyof typeof MESSAGE_FAMILY];\n\nexport const LIFECYCLE_VARIANT = {\n");
    for set in LIFECYCLE_VARIANTS {
        let prefix = set.name.replace('-', "_").to_ascii_uppercase();
        for variant in set.variants {
            output.push_str("  ");
            output.push_str(&prefix);
            output.push('_');
            output.push_str(&variant.name.replace('-', "_").to_ascii_uppercase());
            output.push_str(": [");
            output.push_str(&variant.tag.to_string());
            if let Some(subtag) = variant.subtag {
                output.push_str(", ");
                output.push_str(&subtag.to_string());
            }
            output.push_str("] as const,\n");
        }
    }
    output.push_str(
        "} as const;\n\nexport type LifecycleVariantName = keyof typeof LIFECYCLE_VARIANT;\n\n",
    );
    output.push_str(
        "export interface ActionIntentV1 {\n  readonly actionId: Bytes16;\n  readonly actorId: Bytes16;\n  readonly role: number;\n  readonly environmentId: Bytes16;\n  readonly resourceId: Bytes16;\n  readonly capabilityName: string;\n  readonly operationClass: number;\n  readonly mediaType: string;\n  readonly payload: Uint8Array;\n}\n\nexport interface DigestBoundAmendmentV1 {\n  readonly basePolicyId: Bytes16;\n  readonly successorPolicyId: Bytes16;\n  readonly tier: number;\n  readonly replacementLayer: Uint8Array;\n  readonly amendmentDigest: Sha256;\n}\n\nexport interface DigestBoundAcceptanceContractV1 {\n  readonly acceptanceSpecId: Bytes16;\n  readonly canonicalContent: Uint8Array;\n  readonly contentDigest: Sha256;\n}\n\nexport interface DecodeResult<T> {\n  readonly value: T;\n  readonly grantsAuthority: false;\n}\n",
    );
    output
}

fn push_json_variant(output: &mut String, variant: &VariantTag, comma: bool) {
    output.push_str("      {\"tag\": ");
    output.push_str(&variant.tag.to_string());
    if let Some(subtag) = variant.subtag {
        output.push_str(", \"subtag\": ");
        output.push_str(&subtag.to_string());
    }
    output.push_str(", \"name\": \"");
    output.push_str(variant.name);
    output.push_str("\"}");
    if comma {
        output.push(',');
    }
    output.push('\n');
}
