//! Typed runner failures that remain distinct from subject verdicts.

use peritus_benchmarks::QualificationError;

/// Failure to launch, communicate with, or exercise one disposable integrated subject.
#[derive(Debug, thiserror::Error)]
pub enum SubjectError {
    /// Filesystem, process, or local transport failure.
    #[error("qualification subject I/O failed")]
    Io(#[from] std::io::Error),
    /// Public A3 message construction or validation failed.
    #[error("qualification subject A3 protocol failed")]
    Protocol(#[from] peritus_app_protocol::AppProtocolError),
    /// Canonical command encoding or decoding failed.
    #[error("qualification subject canonical codec failed")]
    Codec(#[from] peritus_codec::CodecError),
    /// The deterministic scheduler rejected a locally constructed transition.
    #[error("qualification subject scheduler transition failed")]
    Scheduler(#[from] peritus_scheduler::SchedulerError),
    /// A benchmark measurement or accounting contract rejected an observation.
    #[error("qualification subject evidence contract failed")]
    Qualification(#[from] QualificationError),
    /// A typed identifier constructor rejected generated bytes.
    #[error("qualification subject identity was invalid: {0:?}")]
    Identifier(peritus_types::IdentifierError),
    /// The finite subject-local identity space was exhausted.
    #[error("qualification subject identity space was exhausted")]
    IdentityExhausted,
    /// The daemon rejected a command without committing an event.
    #[error("qualification daemon rejected command: {0}")]
    CommandRejected(String),
    /// The daemon returned an unexpected A3 frame or command outcome.
    #[error("qualification daemon returned an unexpected protocol result: {0}")]
    UnexpectedResponse(String),
    /// The borrowed subject authorization did not match this disposable instance.
    #[error("qualification subject authorization did not match this instance")]
    AuthorizationMismatch,
    /// A generated daemon configuration could not be constructed.
    #[error("qualification daemon configuration failed: {0}")]
    Configuration(String),
    /// The requested integrated qualification boundary is unavailable on this platform.
    #[error("integrated qualification is unsupported on this platform")]
    UnsupportedPlatform,
}

/// Failure to execute or account one qualification plan.
#[derive(Debug, thiserror::Error)]
pub enum RunnerError<E>
where
    E: std::error::Error + Send + Sync + 'static,
{
    /// The integrated subject rejected or failed one planned operation.
    #[error("qualification subject failed at plan step {step}")]
    Subject {
        /// Zero-based plan step that failed.
        step: u64,
        /// Typed component-owned failure.
        #[source]
        source: E,
    },
    /// The core receipt contract rejected the terminal runner state.
    #[error("qualification receipt was invalid")]
    Receipt(#[source] QualificationError),
}
