//! Typed runner failures that remain distinct from subject verdicts.

use std::io;
use std::path::{Path, PathBuf};

use peritus_benchmarks::QualificationError;

use crate::MachineMismatch;

/// Failure to launch, communicate with, or exercise one disposable integrated subject.
#[derive(Debug, thiserror::Error)]
pub enum SubjectError {
    /// Filesystem, process, or local transport failure.
    #[error("qualification subject I/O failed")]
    Io(#[from] io::Error),
    /// Public A3 message construction or validation failed.
    #[error("qualification subject A3 protocol failed")]
    Protocol(#[from] peritus_app_protocol::AppProtocolError),
    /// Canonical command encoding or decoding failed.
    #[error("qualification subject canonical codec failed")]
    Codec(#[from] peritus_codec::CodecError),
    /// The deterministic scheduler rejected a locally constructed transition.
    #[error("qualification subject scheduler transition failed")]
    Scheduler(#[from] peritus_scheduler::SchedulerError),
    /// A benchmark measurement or accounting contract rejected an observation.
    #[error("qualification subject evidence contract failed")]
    Qualification(#[from] QualificationError),
    /// A typed identifier constructor rejected generated bytes.
    #[error("qualification subject identity was invalid: {0:?}")]
    Identifier(peritus_types::IdentifierError),
    /// The finite subject-local identity space was exhausted.
    #[error("qualification subject identity space was exhausted")]
    IdentityExhausted,
    /// The daemon rejected a command without committing an event.
    #[error("qualification daemon rejected command: {0}")]
    CommandRejected(String),
    /// The daemon returned an unexpected A3 frame or command outcome.
    #[error("qualification daemon returned an unexpected protocol result: {0}")]
    UnexpectedResponse(String),
    /// The borrowed subject authorization did not match this disposable instance.
    #[error("qualification subject authorization did not match this instance")]
    AuthorizationMismatch,
    /// A generated daemon configuration could not be constructed.
    #[error("qualification daemon configuration failed: {0}")]
    Configuration(String),
    /// The requested integrated qualification boundary is unavailable on this platform.
    #[error("integrated qualification is unsupported on this platform")]
    UnsupportedPlatform,
}

/// Failure to coordinate or evaluate one multi-workload H3 campaign.
#[derive(Debug, thiserror::Error)]
pub enum CampaignError {
    /// A stable dataset, sample merge, or evaluation contract failed.
    #[error("qualification campaign contract failed")]
    Qualification(#[from] QualificationError),
    /// One workload runner could not produce a terminal receipt.
    #[error("qualification campaign runner failed")]
    Runner(#[from] RunnerError<SubjectError>),
    /// A disposable subject could not launch or negotiate its public boundary.
    #[error("qualification campaign subject failed")]
    Subject(#[from] SubjectError),
    /// A worker thread panicked instead of returning typed evidence.
    #[error("qualification campaign worker panicked")]
    WorkerPanicked,
    /// Different disposable subjects reported different executable identities.
    #[error("qualification campaign subjects did not share one exact executable identity")]
    SubjectIdentityMismatch,
    /// The measured host did not match the production profile.
    #[error("qualification host does not match reference-machine fields: {mismatches:?}")]
    ReferenceMachineMismatch {
        /// Every mismatched field in stable contract order.
        mismatches: Vec<MachineMismatch>,
    },
    /// No workloads matched the selected campaign mode.
    #[error("qualification campaign selected no workloads")]
    NoWorkloads,
    /// System time could not be represented relative to the Unix epoch.
    #[error("qualification campaign clock was before the Unix epoch")]
    Clock(#[from] std::time::SystemTimeError),
}

/// Failure to validate or atomically retain one H3 evidence bundle.
#[derive(Debug, thiserror::Error)]
pub enum EvidenceError {
    /// Stable H3 input or report construction failed.
    #[error("qualification evidence contract failed")]
    Qualification(#[from] QualificationError),
    /// Exact profile or workload bytes do not describe the executed dataset.
    #[error("retained profile or workload document does not match the executed dataset")]
    DatasetMismatch,
    /// Exact accepted-baseline bytes do not describe the baseline used for evaluation.
    #[error("retained accepted-baseline document does not match the evaluated baseline")]
    BaselineMismatch,
    /// A retained executable did not match the identity recorded during execution.
    #[error("{role} executable digest mismatch: expected {expected}, observed {observed}")]
    ExecutableDigestMismatch {
        /// Executable role being retained.
        role: &'static str,
        /// Digest recorded by the campaign.
        expected: String,
        /// Digest recomputed while copying evidence.
        observed: String,
    },
    /// Evidence publication never replaces an existing path.
    #[error("qualification evidence output already exists: {0}")]
    OutputExists(PathBuf),
    /// An evidence source or output path was not a regular file or usable directory target.
    #[error("invalid qualification evidence path: {0}")]
    InvalidPath(PathBuf),
    /// A bounded filesystem operation failed.
    #[error("could not {operation} at {}", path.display())]
    Io {
        /// Stable operation description.
        operation: &'static str,
        /// Path acted on.
        path: PathBuf,
        /// Operating-system error.
        #[source]
        source: io::Error,
    },
}

impl EvidenceError {
    pub(crate) fn io(operation: &'static str, path: &Path, source: io::Error) -> Self {
        Self::Io { operation, path: path.to_path_buf(), source }
    }
}

/// Failure to observe the current host for H3 reference-machine admission.
#[derive(Debug, thiserror::Error)]
pub enum MachineProbeError {
    /// A local operating-system query failed.
    #[error("could not {operation} while probing the H3 host")]
    Io {
        /// Stable query description.
        operation: &'static str,
        /// Operating-system error.
        #[source]
        source: io::Error,
    },
    /// A required fact was absent from otherwise readable host metadata.
    #[error("H3 host probe did not report {0}")]
    Missing(&'static str),
    /// A host fact could not be represented by the stable H3 schema.
    #[error("H3 host probe reported invalid {0}")]
    Invalid(&'static str),
    /// The current Unix family has no reviewed probe implementation.
    #[error("H3 host probe is unsupported on this operating system")]
    Unsupported,
    /// Stable machine construction rejected the observed facts.
    #[error("H3 host probe did not satisfy the machine schema")]
    Qualification(#[from] QualificationError),
}

impl MachineProbeError {
    pub(crate) const fn io(operation: &'static str, source: io::Error) -> Self {
        Self::Io { operation, source }
    }
}

/// Failure to parse or execute the `peritus-h3` operator command.
#[derive(Debug, thiserror::Error)]
pub enum OperatorError {
    /// The user requested command help.
    #[error("help requested")]
    HelpRequested,
    /// Command arguments were missing, duplicated, or unknown.
    #[error("invalid peritus-h3 arguments: {0}")]
    Usage(String),
    /// A bounded input or executable filesystem operation failed.
    #[error("could not {operation} at {}", path.display())]
    Io {
        /// Stable operation description.
        operation: &'static str,
        /// Path acted on.
        path: PathBuf,
        /// Operating-system error.
        #[source]
        source: io::Error,
    },
    /// A JSON input, identifier, or runner descriptor was invalid.
    #[error("H3 operator input contract failed")]
    Qualification(#[from] QualificationError),
    /// Current-host observation failed.
    #[error("H3 operator host probe failed")]
    Probe(#[from] MachineProbeError),
    /// Campaign execution or evaluation failed.
    #[error("H3 operator campaign failed")]
    Campaign(#[from] CampaignError),
    /// Atomic evidence publication failed.
    #[error("H3 operator evidence publication failed")]
    Evidence(#[from] EvidenceError),
    /// The system clock cannot supply a portable run identifier.
    #[error("H3 operator clock was before the Unix epoch")]
    Clock(#[from] std::time::SystemTimeError),
}

impl OperatorError {
    pub(crate) fn io(operation: &'static str, path: &Path, source: io::Error) -> Self {
        Self::Io { operation, path: path.to_path_buf(), source }
    }
}

/// Failure to execute or account one qualification plan.
#[derive(Debug, thiserror::Error)]
pub enum RunnerError<E>
where
    E: std::error::Error + Send + Sync + 'static,
{
    /// The integrated subject rejected or failed one planned operation.
    #[error("qualification subject failed at plan step {step}")]
    Subject {
        /// Zero-based plan step that failed.
        step: u64,
        /// Typed component-owned failure.
        #[source]
        source: E,
    },
    /// The core receipt contract rejected the terminal runner state.
    #[error("qualification receipt was invalid")]
    Receipt(#[source] QualificationError),
}
