//! TypeScript declaration rendering for the lossless JSON projection.

use std::collections::BTreeSet;

use super::super::{
    APP_ERROR_CODES, APP_FAMILIES, APP_FLOW_TYPES, APP_NESTED_TYPES, AppTypeDescriptor, JsonShape,
};

pub(super) fn render() -> String {
    let descriptors = APP_NESTED_TYPES
        .iter()
        .chain(APP_FLOW_TYPES)
        .flat_map(|group| group.iter())
        .collect::<Vec<_>>();
    let mut output = String::from(
        "// @generated by peritus-app-protocol-codegen; do not edit.\n\nexport type OpaqueId<Brand extends string> = string & { readonly __brand: Brand };\nexport type UInt64 = string & { readonly __brand: \"UInt64\" };\nexport type Base64Bytes = string & { readonly __brand: \"Base64Bytes\" };\nexport type Sha256Digest = string & { readonly __brand: \"Sha256Digest\" };\n",
    );
    for identifier in identifier_types(&descriptors) {
        output.push_str("export type ");
        output.push_str(identifier);
        output.push_str(" = OpaqueId<\"");
        output.push_str(identifier);
        output.push_str("\">;\n");
    }
    output.push_str("\nexport type AppFamily = ");
    separated_with(&mut output, APP_FAMILIES.iter().map(|family| family.tag.to_string()), " | ");
    output.push_str(";\nexport type AppPayloadKind =\n");
    render_string_union(
        &mut output,
        APP_FAMILIES.iter().flat_map(|family| family.payloads.iter()).map(|payload| payload.name),
    );
    output.push_str(";\n\nexport type AppErrorCode =\n");
    render_string_union(&mut output, APP_ERROR_CODES.iter().map(|error| error.name));
    output.push_str(";\n\n");
    for descriptor in descriptors {
        render_interface(&mut output, descriptor);
    }
    output.push_str(
        "export interface CanonicalAppMessage {\n  readonly family: AppFamily;\n  readonly schemaVersion: 1;\n  readonly payloadKind: AppPayloadKind;\n  readonly payload: Base64Bytes;\n}\n",
    );
    output
}

fn identifier_types(descriptors: &[&AppTypeDescriptor]) -> BTreeSet<&'static str> {
    descriptors
        .iter()
        .flat_map(|descriptor| descriptor.fields)
        .filter(|field| matches!(field.json_shape, JsonShape::Identifier))
        .map(|field| field.typescript_type)
        .collect()
}

fn render_interface(output: &mut String, descriptor: &AppTypeDescriptor) {
    output.push_str("export interface ");
    output.push_str(descriptor.name);
    output.push_str(" {\n");
    for field in descriptor.fields {
        output.push_str("  readonly ");
        output.push_str(field.name);
        if !field.required {
            output.push('?');
        }
        output.push_str(": ");
        output.push_str(field.typescript_type);
        output.push_str(";\n");
    }
    output.push_str("}\n\n");
}

fn render_string_union<'a>(output: &mut String, values: impl Iterator<Item = &'a str>) {
    for (index, value) in values.enumerate() {
        output.push_str(if index == 0 { "  \"" } else { "  | \"" });
        output.push_str(value);
        output.push_str("\"\n");
    }
}

fn separated_with(output: &mut String, values: impl Iterator<Item = String>, separator: &str) {
    for (index, value) in values.enumerate() {
        if index > 0 {
            output.push_str(separator);
        }
        output.push_str(&value);
    }
}
