//! Stable human-readable command synopsis.

use std::ffi::OsStr;

const COMMANDS: &[&str] = &[
    "--version",
    "serve --config <config.toml>",
    "qualify-pty",
    "qualify-blob-before-stage --config <config.toml>",
    "qualify-blob-before-recover --config <config.toml>",
    "qualify-blob-after-stage --config <config.toml>",
    "qualify-blob-after-recover --config <config.toml>",
    "qualify-blob-corruption-stage --config <config.toml>",
    "qualify-blob-corruption-recover --config <config.toml>",
    "qualify-disk-blob-finalize-stage --config <config.toml>",
    "qualify-disk-blob-finalize-recover --config <config.toml>",
    "qualify-disk-journal-append-stage --config <config.toml>",
    "qualify-disk-journal-append-recover --config <config.toml>",
    "qualify-journal-before-stage --config <config.toml>",
    "qualify-journal-before-recover --config <config.toml>",
    "qualify-journal-corruption-stage --config <config.toml>",
    "qualify-journal-corruption-recover --config <config.toml>",
    "qualify-evidence-corruption-stage --config <config.toml>",
    "qualify-evidence-corruption-recover --config <config.toml>",
    "qualify-promotion-evidence-corruption-stage --config <config.toml>",
    "qualify-promotion-evidence-corruption-recover --config <config.toml>",
    "qualify-snapshot-before-stage --config <config.toml>",
    "qualify-snapshot-before-recover --config <config.toml>",
    "qualify-snapshot-after-stage --config <config.toml>",
    "qualify-snapshot-after-recover --config <config.toml>",
    "qualify-snapshot-corruption-stage --config <config.toml>",
    "qualify-snapshot-corruption-recover --config <config.toml>",
    "qualify-disk-snapshot-commit-stage --config <config.toml>",
    "qualify-disk-snapshot-commit-recover --config <config.toml>",
    "qualify-lease-before-stage --config <config.toml>",
    "qualify-lease-before-recover --config <config.toml>",
    "qualify-lease-after-stage --config <config.toml>",
    "qualify-lease-after-recover --config <config.toml>",
    "qualify-patch-before-stage --config <config.toml>",
    "qualify-patch-before-recover --config <config.toml>",
    "qualify-patch-after-stage --config <config.toml>",
    "qualify-patch-after-recover --config <config.toml>",
    "qualify-gate-before-stage --config <config.toml>",
    "qualify-gate-before-recover --config <config.toml>",
    "qualify-gate-after-stage --config <config.toml>",
    "qualify-gate-after-recover --config <config.toml>",
    "qualify-promotion-before-stage --config <config.toml>",
    "qualify-promotion-before-recover --config <config.toml>",
    "qualify-promotion-after-stage --config <config.toml>",
    "qualify-promotion-after-recover --config <config.toml>",
    "qualify-projection-corruption-stage --config <config.toml>",
    "qualify-projection-corruption-recover --config <config.toml>",
    "qualify-dependency-stage <provider|tool|worker> <death|retry-exhaustion> --attempts <count> --config <config.toml>",
    "qualify-dependency-recover <provider|tool|worker> <death|retry-exhaustion> --attempts <count> --config <config.toml>",
    "qualify-dependency-child <provider|tool|worker>",
    "qualify-daemon-lifecycle-stage <phase> --config <config.toml>",
    "qualify-daemon-lifecycle-recover <phase> --config <config.toml>",
    "qualify-outbox-stage --config <config.toml>",
    "qualify-outbox-recover --config <config.toml>",
    "qualify-reboot-outstanding-stage --config <config.toml>",
    "qualify-reboot-outstanding-recover --config <config.toml>",
    "qualify-reboot-durable-stage --config <config.toml>",
    "qualify-reboot-durable-recover --config <config.toml>",
    "qualify-reboot-startup-stage --config <config.toml>",
    "qualify-reboot-startup-reconciliation-stage --config <config.toml>",
    "qualify-reboot-startup-recover --config <config.toml>",
];

pub(super) fn write(executable: &OsStr) {
    super::write_error(&format!(
        "usage: {} {}",
        std::path::Path::new(executable).display(),
        COMMANDS.join(" | "),
    ));
}
