//! Stable human-readable command synopsis.

use std::ffi::OsStr;

pub(super) fn write(executable: &OsStr) {
    super::write_error(&format!(
        "usage: {} --version | serve --config <config.toml> | qualify-pty | qualify-blob-before-stage --config <config.toml> | qualify-blob-before-recover --config <config.toml> | qualify-blob-after-stage --config <config.toml> | qualify-blob-after-recover --config <config.toml> | qualify-blob-corruption-stage --config <config.toml> | qualify-blob-corruption-recover --config <config.toml> | qualify-journal-before-stage --config <config.toml> | qualify-journal-before-recover --config <config.toml> | qualify-journal-corruption-stage --config <config.toml> | qualify-journal-corruption-recover --config <config.toml> | qualify-snapshot-before-stage --config <config.toml> | qualify-snapshot-before-recover --config <config.toml> | qualify-snapshot-after-stage --config <config.toml> | qualify-snapshot-after-recover --config <config.toml> | qualify-lease-before-stage --config <config.toml> | qualify-lease-before-recover --config <config.toml> | qualify-lease-after-stage --config <config.toml> | qualify-lease-after-recover --config <config.toml> | qualify-patch-before-stage --config <config.toml> | qualify-patch-before-recover --config <config.toml> | qualify-patch-after-stage --config <config.toml> | qualify-patch-after-recover --config <config.toml> | qualify-gate-before-stage --config <config.toml> | qualify-gate-before-recover --config <config.toml> | qualify-gate-after-stage --config <config.toml> | qualify-gate-after-recover --config <config.toml> | qualify-promotion-before-stage --config <config.toml> | qualify-promotion-before-recover --config <config.toml> | qualify-promotion-after-stage --config <config.toml> | qualify-promotion-after-recover --config <config.toml> | qualify-projection-corruption-stage --config <config.toml> | qualify-projection-corruption-recover --config <config.toml> | qualify-outbox-stage --config <config.toml> | qualify-outbox-recover --config <config.toml>",
        std::path::Path::new(executable).display(),
    ));
}
