//! Reproducible native H0 candidate and host-fact preparation.

mod args;
mod candidate;
mod host;

use std::env;
use std::ffi::OsString;
use std::fs;
use std::io::Write as _;
use std::path::Path;

use crate::repository::{CandidateRepository, RepositoryError};

use self::args::Options;

/// Failure to derive or publish one exact H0 native-shard input set.
#[derive(Debug, thiserror::Error)]
enum PreparationError {
    /// The fixed command-line interface was not followed exactly.
    #[error("{0}")]
    Arguments(&'static str),
    /// The candidate repository could not be admitted or inspected.
    #[error(transparent)]
    Repository(#[from] RepositoryError),
    /// A filesystem operation failed.
    #[error("H0 preparation {operation} `{path}`: {source}")]
    Io {
        operation: &'static str,
        path: String,
        #[source]
        source: std::io::Error,
    },
    /// Candidate metadata did not satisfy the reviewed protocol.
    #[error("H0 preparation metadata: {0}")]
    Metadata(&'static str),
    /// A candidate or host document could not be encoded.
    #[error("H0 preparation JSON: {0}")]
    Json(#[from] serde_json::Error),
    /// The workspace manifest could not be decoded.
    #[error("H0 preparation manifest: {0}")]
    Toml(#[from] toml::de::Error),
    /// The public H0 candidate interchange rejected generated bytes.
    #[error(transparent)]
    Qualification(#[from] crate::QualificationError),
}

impl PreparationError {
    fn io(operation: &'static str, path: &Path, source: std::io::Error) -> Self {
        Self::Io { operation, path: path.display().to_string(), source }
    }
}

/// Derives the exact candidate and native host document and publishes a fresh shard workspace.
///
/// # Errors
///
/// Rejects malformed arguments, dirty or non-Peritus candidates, cross-platform claims,
/// non-regular controllers, output collisions, metadata failures, and incomplete publication.
pub fn run_from_env() -> Result<(), Box<dyn std::error::Error>> {
    let arguments = env::args_os().skip(1).collect::<Vec<_>>();
    run(&arguments).map_err(Into::into)
}

fn run(arguments: &[OsString]) -> Result<(), PreparationError> {
    let options = Options::parse(arguments)?;
    if crate::QualificationPlatform::current() != Some(options.platform) {
        return Err(PreparationError::Metadata(
            "requested H0 platform does not match the native executable",
        ));
    }
    let repository = CandidateRepository::open(&options.candidate_root)?;
    repository.verify_clean()?;
    let controller = fs::canonicalize(&options.controller).map_err(|source| {
        PreparationError::io("canonicalize reviewed controller", &options.controller, source)
    })?;
    let candidate = candidate::prepare(&repository)?;
    let host_facts = host::document(&repository, &candidate, &controller, options.platform)?;
    publish(&options.output, &candidate.bytes, &host_facts)?;
    println!(
        "prepared H0 {} shard inputs for {} in {}",
        options.platform.as_str(),
        candidate.commit,
        options.output.display()
    );
    Ok(())
}

fn publish(output: &Path, candidate: &[u8], host_facts: &[u8]) -> Result<(), PreparationError> {
    if output.exists() {
        return Err(PreparationError::Metadata("H0 output directory already exists"));
    }
    let parent = output.parent().unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent)
        .map_err(|source| PreparationError::io("create output parent", parent, source))?;
    let parent = fs::canonicalize(parent)
        .map_err(|source| PreparationError::io("canonicalize output parent", parent, source))?;
    let name = output
        .file_name()
        .ok_or(PreparationError::Metadata("H0 output directory has no final name"))?;
    let destination = parent.join(name);
    if destination.exists() {
        return Err(PreparationError::Metadata("H0 output directory already exists"));
    }
    let temporary = tempfile::Builder::new()
        .prefix("peritus-h0-prepare-")
        .tempdir_in(&parent)
        .map_err(|source| PreparationError::io("create output temporary", &parent, source))?;
    write_file(&temporary.path().join("candidate.json"), candidate)?;
    write_file(&temporary.path().join("host-facts.json"), host_facts)?;
    for directory in ["scratch", "artifacts"] {
        let path = temporary.path().join(directory);
        fs::create_dir(&path)
            .map_err(|source| PreparationError::io("create shard directory", &path, source))?;
    }
    fs::rename(temporary.path(), &destination)
        .map_err(|source| PreparationError::io("publish shard workspace", &destination, source))?;
    Ok(())
}

fn write_file(path: &Path, bytes: &[u8]) -> Result<(), PreparationError> {
    let mut file = fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .map_err(|source| PreparationError::io("create prepared document", path, source))?;
    file.write_all(bytes)
        .and_then(|()| file.sync_all())
        .map_err(|source| PreparationError::io("persist prepared document", path, source))
}
