use super::*;

#[test]
fn flattened_gitlink_source_remains_visible_to_review_and_fingerprints() {
    let root = repository();
    let nested = root.path().join("nested");
    fs::rename(repository().keep(), &nested).unwrap();
    fs::write(nested.join(".gitignore"), "secret.txt\ntarget/\n").unwrap();
    fs::write(nested.join("secret.txt"), "private ignored value\n").unwrap();
    git(root.path(), &["add", "nested"], None).unwrap();
    let baseline = ManagedBaseline::capture(root.path(), true).unwrap();
    fs::remove_dir_all(nested.join(".git")).unwrap();
    let before = ManagedBaseline::repository_fingerprint(root.path()).unwrap();
    let source_before = ManagedBaseline::source_digest(root.path()).unwrap();
    fs::write(nested.join("tracked.txt"), "flattened task edit\n").unwrap();
    let after = ManagedBaseline::repository_fingerprint(root.path()).unwrap();
    let source_after = ManagedBaseline::source_digest(root.path()).unwrap();
    assert_ne!(before, after, "qualification must see edits beneath the former gitlink");
    assert_ne!(source_before, source_after, "commit retry must detect intervening source edits");
    let paths = baseline.changed_paths(root.path()).unwrap();
    assert!(paths.contains(&PathBuf::from("nested/tracked.txt")));
    assert!(!paths.contains(&PathBuf::from("nested/secret.txt")));
    let patch = String::from_utf8(baseline.patch(root.path()).unwrap()).unwrap();
    assert!(patch.contains("+flattened task edit"));
    assert!(!patch.contains("private ignored value"));
}

#[test]
fn flattened_directory_scan_is_literal_and_keeps_prior_owned_ignored_source() {
    let root = repository();
    let nested = root.path().join("nested[ab]");
    fs::rename(repository().keep(), &nested).unwrap();
    fs::create_dir(nested.join("build")).unwrap();
    fs::write(nested.join("build/maintained.txt"), "prior maintained source\n").unwrap();
    git(&nested, &["add", "build/maintained.txt"], None).unwrap();
    git(root.path(), &["add", "nested[ab]"], None).unwrap();
    let baseline = ManagedBaseline::capture(root.path(), true).unwrap();
    let index = git(root.path(), &["ls-files", "--stage", "-z"], None).unwrap();
    fs::remove_dir_all(nested.join(".git")).unwrap();
    fs::write(nested.join(".gitignore"), "tracked.txt\n").unwrap();
    fs::write(nested.join("tracked.txt"), "still owned source\n").unwrap();
    fs::write(nested.join("build/maintained.txt"), "changed maintained source\n").unwrap();
    fs::write(nested.join("build/generated.txt"), "exclude generated bytes\n").unwrap();
    let paths = baseline.changed_paths(root.path()).unwrap();
    assert!(paths.contains(&PathBuf::from("nested[ab]/tracked.txt")));
    assert!(paths.contains(&PathBuf::from("nested[ab]/build/maintained.txt")));
    assert!(!paths.contains(&PathBuf::from("nested[ab]/build/generated.txt")));
    let patch = String::from_utf8(baseline.patch(root.path()).unwrap()).unwrap();
    assert!(patch.contains("+still owned source"));
    assert!(patch.contains("+changed maintained source"));
    assert!(!patch.contains("exclude generated bytes"));
    assert_eq!(git(root.path(), &["ls-files", "--stage", "-z"], None).unwrap(), index);
}

#[test]
fn discard_restores_removed_git_directory_and_preserves_flattened_task_files() {
    let root = repository();
    let nested = root.path().join("nested");
    fs::rename(repository().keep(), &nested).unwrap();
    fs::write(nested.join("tracked.txt"), "user staged\n").unwrap();
    git(&nested, &["add", "tracked.txt"], None).unwrap();
    fs::write(nested.join("tracked.txt"), "user working\n").unwrap();
    let index = git(&nested, &["ls-files", "--stage", "-z"], None).unwrap();
    let baseline = ManagedBaseline::capture(root.path(), true).unwrap();
    fs::remove_dir_all(nested.join(".git")).unwrap();
    fs::write(nested.join("tracked.txt"), "task changed\n").unwrap();
    fs::write(nested.join("new.txt"), "task created\n").unwrap();
    let paths = baseline.changed_paths(root.path()).unwrap();
    let recovered = baseline.discard(root.path(), &paths).expect("restore flattened repository");
    assert_eq!(fs::read(nested.join("tracked.txt")).unwrap(), b"user working\n");
    assert_eq!(git(&nested, &["ls-files", "--stage", "-z"], None).unwrap(), index);
    assert!(!nested.join("new.txt").exists());
    assert_eq!(recovered.len(), 1);
    assert_eq!(fs::read(recovered[0].join("repository/tracked.txt")).unwrap(), b"task changed\n");
    assert_eq!(fs::read(recovered[0].join("repository/new.txt")).unwrap(), b"task created\n");
    assert!(baseline.changed_paths(root.path()).unwrap().is_empty());
}

#[cfg(unix)]
#[test]
fn flattened_directory_scan_does_not_follow_external_symlinks() {
    let root = repository();
    let outside = tempfile::tempdir().unwrap();
    let nested = root.path().join("nested");
    fs::rename(repository().keep(), &nested).unwrap();
    git(root.path(), &["add", "nested"], None).unwrap();
    fs::remove_dir_all(nested.join(".git")).unwrap();
    fs::write(outside.path().join("secret.txt"), "outside one\n").unwrap();
    std::os::unix::fs::symlink(outside.path(), nested.join("link")).unwrap();
    let before = ManagedBaseline::repository_fingerprint(root.path()).unwrap();
    fs::write(outside.path().join("secret.txt"), "outside two\n").unwrap();
    assert_eq!(ManagedBaseline::repository_fingerprint(root.path()).unwrap(), before);
    let snapshot = ManagedBaseline::capture(root.path(), false).unwrap();
    assert_eq!(snapshot.entries["nested/link"].mode, "120000");
    assert!(!snapshot.entries.contains_key("nested/link/secret.txt"));
}
