//! Negotiation hello and outer-envelope field metadata.

use super::super::super::{
    AppTypeDescriptor, CanonicalWireType, FieldBound as B, JsonShape as J, field,
};

pub(in crate::schema::fields::types) const HANDSHAKE_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "ClientHelloData",
        rust_type: "ClientHello",
        fields: &[
            field(
                "protocolId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "ProtocolId",
                "ProtocolId",
                J::Identifier,
                true,
            ),
            field(
                "requestedSessionId",
                CanonicalWireType::Option,
                &[B::NonZero],
                "Option<SessionId>",
                "SessionId",
                J::Identifier,
                false,
            ),
            field(
                "versions",
                CanonicalWireType::Sequence,
                &[B::NonZero, B::Versions, B::SortedUnique],
                "Vec<VersionRange>",
                "readonly VersionRange[]",
                J::ArrayRef("VersionRange"),
                true,
            ),
            field(
                "requiredFeatures",
                CanonicalWireType::Sequence,
                &[B::Features, B::SortedUnique],
                "ProtocolFeatureSet",
                "readonly string[]",
                J::StringArray,
                true,
            ),
            field(
                "optionalFeatures",
                CanonicalWireType::Sequence,
                &[B::Features, B::SortedUnique],
                "ProtocolFeatureSet",
                "readonly string[]",
                J::StringArray,
                true,
            ),
            field(
                "receiveLimits",
                CanonicalWireType::Struct,
                &[],
                "AppProtocolLimits",
                "AppProtocolLimits",
                J::Ref("AppProtocolLimits"),
                true,
            ),
            field(
                "implementation",
                CanonicalWireType::Utf8,
                &[B::CodecStringBytes],
                "ImplementationMetadata",
                "string",
                J::String,
                true,
            ),
            field(
                "establishedSessionId",
                CanonicalWireType::Option,
                &[B::NonZero],
                "Option<SessionId>",
                "SessionId",
                J::Identifier,
                false,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ServerHelloPreamble",
        rust_type: "ServerHello",
        fields: &[
            field(
                "protocolId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "ProtocolId",
                "ProtocolId",
                J::Identifier,
                true,
            ),
            field(
                "implementation",
                CanonicalWireType::Utf8,
                &[B::CodecStringBytes],
                "ImplementationMetadata",
                "string",
                J::String,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "RequestEnvelopeFields",
        rust_type: "AppRequestEnvelope",
        fields: &[
            field(
                "context",
                CanonicalWireType::Struct,
                &[],
                "ProtocolContext",
                "ProtocolContext",
                J::Ref("ProtocolContext"),
                true,
            ),
            field(
                "requestId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "RequestId",
                "RequestId",
                J::Identifier,
                true,
            ),
            field(
                "correlationId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "CorrelationId",
                "CorrelationId",
                J::Identifier,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ResponseEnvelopeFields",
        rust_type: "AppResponseEnvelope",
        fields: &[
            field(
                "context",
                CanonicalWireType::Struct,
                &[],
                "ProtocolContext",
                "ProtocolContext",
                J::Ref("ProtocolContext"),
                true,
            ),
            field(
                "requestId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "RequestId",
                "RequestId",
                J::Identifier,
                true,
            ),
            field(
                "correlationId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "CorrelationId",
                "CorrelationId",
                J::Identifier,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "EventEnvelopeFields",
        rust_type: "AppEventEnvelope",
        fields: &[field(
            "context",
            CanonicalWireType::Struct,
            &[],
            "ProtocolContext",
            "ProtocolContext",
            J::Ref("ProtocolContext"),
            true,
        )],
    },
    AppTypeDescriptor {
        name: "ControlEnvelopeFields",
        rust_type: "ControlEnvelope",
        fields: &[
            field(
                "context",
                CanonicalWireType::Struct,
                &[],
                "ProtocolContext",
                "ProtocolContext",
                J::Ref("ProtocolContext"),
                true,
            ),
            field(
                "correlationId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "CorrelationId",
                "CorrelationId",
                J::Identifier,
                true,
            ),
        ],
    },
];
