//! Version, context, resource-limit, and revision field metadata.

use super::super::super::{
    AppTypeDescriptor, CanonicalWireType, FieldBound as B, JsonShape as J, field,
};

pub(in crate::schema::fields::types) const VERSION_LIMIT_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "ProtocolVersion",
        rust_type: "ProtocolVersion",
        fields: &[
            field("major", CanonicalWireType::U16, &[B::NonZero], "u16", "number", J::U16, true),
            field("minor", CanonicalWireType::U16, &[], "u16", "number", J::U16, true),
        ],
    },
    AppTypeDescriptor {
        name: "VersionRange",
        rust_type: "VersionRange",
        fields: &[
            field("major", CanonicalWireType::U16, &[B::NonZero], "u16", "number", J::U16, true),
            field("minorMin", CanonicalWireType::U16, &[], "u16", "number", J::U16, true),
            field("minorMax", CanonicalWireType::U16, &[], "u16", "number", J::U16, true),
        ],
    },
    AppTypeDescriptor {
        name: "ProtocolContext",
        rust_type: "ProtocolContext",
        fields: &[
            field(
                "protocolId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "ProtocolId",
                "ProtocolId",
                J::Identifier,
                true,
            ),
            field(
                "version",
                CanonicalWireType::Struct,
                &[],
                "ProtocolVersion",
                "ProtocolVersion",
                J::Ref("ProtocolVersion"),
                true,
            ),
            field(
                "sessionId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "SessionId",
                "SessionId",
                J::Identifier,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "CodecLimits",
        rust_type: "CodecLimits",
        fields: &[
            field(
                "maxFrameBytes",
                CanonicalWireType::U64,
                &[B::NonZero],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maxPayloadBytes",
                CanonicalWireType::U64,
                &[B::NonZero],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maxCollectionItems",
                CanonicalWireType::U64,
                &[B::NonZero],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maxStringBytes",
                CanonicalWireType::U64,
                &[B::NonZero],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maxOpaqueBytes",
                CanonicalWireType::U64,
                &[B::NonZero],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maxNestingDepth",
                CanonicalWireType::U16,
                &[B::NonZero],
                "u16",
                "number",
                J::U16,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "AppProtocolLimits",
        rust_type: "AppProtocolLimits",
        fields: &[
            field(
                "codec",
                CanonicalWireType::Struct,
                &[],
                "CodecLimits",
                "CodecLimits",
                J::Ref("CodecLimits"),
                true,
            ),
            field(
                "maxVersions",
                CanonicalWireType::U64,
                &[B::NonZero, B::Versions],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maxFeatures",
                CanonicalWireType::U64,
                &[B::NonZero, B::Features],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maxIdempotencyEntries",
                CanonicalWireType::U64,
                &[B::NonZero, B::CodecCollectionItems],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maxTopics",
                CanonicalWireType::U64,
                &[B::NonZero, B::Topics],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maxInFlightEvents",
                CanonicalWireType::U64,
                &[B::NonZero, B::InFlightEvents],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maxArtifactChunkBytes",
                CanonicalWireType::U64,
                &[B::NonZero, B::ArtifactChunkBytes],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maxPromptChoices",
                CanonicalWireType::U64,
                &[B::NonZero, B::PromptChoices],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maxTerminalChunkBytes",
                CanonicalWireType::U64,
                &[B::NonZero, B::TerminalChunkBytes],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maxDiagnosticBytes",
                CanonicalWireType::U64,
                &[B::NonZero, B::DiagnosticBytes],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "maxRemainingWorkItems",
                CanonicalWireType::U64,
                &[B::NonZero, B::RemainingWorkItems],
                "usize",
                "UInt64",
                J::U64String,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "NegotiatedProtocol",
        rust_type: "NegotiatedProtocol",
        fields: &[
            field(
                "version",
                CanonicalWireType::Struct,
                &[],
                "ProtocolVersion",
                "ProtocolVersion",
                J::Ref("ProtocolVersion"),
                true,
            ),
            field(
                "features",
                CanonicalWireType::Sequence,
                &[B::Features, B::SortedUnique],
                "ProtocolFeatureSet",
                "readonly string[]",
                J::StringArray,
                true,
            ),
            field(
                "limits",
                CanonicalWireType::Struct,
                &[],
                "AppProtocolLimits",
                "AppProtocolLimits",
                J::Ref("AppProtocolLimits"),
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "IncompatibilityReason",
        rust_type: "IncompatibilityReason",
        fields: &[
            field(
                "reason",
                CanonicalWireType::U8,
                &[],
                "IncompatibilityReason",
                "\"no-common-version\" | \"missing-required-features\"",
                J::Enum(&["no-common-version", "missing-required-features"]),
                true,
            ),
            field(
                "missingRequiredFeatures",
                CanonicalWireType::Sequence,
                &[B::Features, B::SortedUnique],
                "ProtocolFeatureSet",
                "readonly string[]",
                J::StringArray,
                false,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "RevisionTuple",
        rust_type: "RevisionTuple",
        fields: &[
            field(
                "acceptanceSpecId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "AcceptanceSpecId",
                "AcceptanceSpecId",
                J::Identifier,
                true,
            ),
            field(
                "harnessId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "HarnessId",
                "HarnessId",
                J::Identifier,
                true,
            ),
            field(
                "workspaceId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "WorkspaceId",
                "WorkspaceId",
                J::Identifier,
                true,
            ),
            field(
                "workspaceGeneration",
                CanonicalWireType::U64,
                &[B::NonZero],
                "Generation",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "workspaceRevision",
                CanonicalWireType::U64,
                &[B::NonZero],
                "RevisionNumber",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "policyId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "PolicyId",
                "PolicyId",
                J::Identifier,
                true,
            ),
            field(
                "providerProfileId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "ProviderProfileId",
                "ProviderProfileId",
                J::Identifier,
                true,
            ),
        ],
    },
];
