use super::*;

const REQUIRED_WORKFLOW_TERMS: &[&str] = &[
    "500 lines",
    "module",
    "distinguish ignored authority",
    "Judge the requested outcome",
    "Benign advice",
    "Trigger words",
    "acceptance evidence",
    "never delete a file",
    "literal requirement ledger",
    "grammatically modify",
    "explicit expected value",
    "grammatically ambiguous compound rule",
    "violates every reasonable reading",
    "that is circular",
    "nearest-item grammatical attachments",
    "authoritative label, taxonomy, or definition",
    "literal category boundary",
    "separately named output fields",
    "derive membership independently",
    "detail ledger is named for one member",
    "as a projection",
    "of that class only",
    "other nonmatching",
    "classes into the ledger",
    "preserve explicit routing",
    "does not also belong in a reject ledger",
    "most specific",
    "no matching source record",
    "reserve `invalid`",
    "material condition",
    "union of unresolved",
    "explicit identity",
    "exclude ignored or out-of-window IDs",
    "snapshot's own temporal boundary",
    "explicit past-time (`as of` or `at <time>`)",
    "historical-date, version, or revision",
    "contemporaneous",
    "source revision",
    "archived record",
    "current mutable source filtered",
    "release, creation, or effective date",
    "later backfills and recomputation",
    "historical fact",
    "immutable manifest, index, or tree",
    "relevant object sizes",
    "Client-side sparse",
    "patterns do not by themselves",
    "through clone,",
    "archive, or fetch variants",
    "materially bounded or resumable",
    "published aggregate's meaning",
    "missing-data",
    "revision-joining",
    "similarly named source with",
    "provisional artifact unchanged",
    "constraints as evidence-positive",
    "source field does not prove",
    "Exclude an unproven option",
    "source aggregates",
    "does not prove that an aggregate is pre-adjustment",
    "record-level join",
    "inventing a transformation",
    "non-exhaustive",
    "invented allowlist",
    "closed mutation contract",
    "every changed path and token",
    "helpful adjacent",
    "preserve that precedence",
    "controlling source",
    "owns the primary field",
    "broader base rule as secondary",
    "one losing-source collection",
    "priority, effective date",
    "globally obsolete",
    "source-reference collection",
    "every collection element as the exact",
    "source identity and put",
    "breaks exact matching, joins, and deduplication",
    "do not copy that literal",
    "without restating the value",
    "from being mistaken for an answer",
    "independently resolvable",
    "exact counterexample identity",
    "richer sibling output",
    "Every artifact that records `not_reproducible`",
    "literal source",
    "spelling.",
    "location field itself",
    "in signal or rationale",
    "generic location",
    "decision values self-contained",
    "included and excluded scope",
    "must not carry material",
    "decisive evidence for that disposition",
    "record anchor in the source identity",
    "relative/path#record_id",
    "one canonical decision record",
    "leave the canonical",
    "decided governing requirement",
    "final governing decision",
    "open question about whether it has been satisfied",
    "clause that makes the item required",
    "failed validity condition",
    "Boundary and limitation documents",
    "allowed administrative scope positively",
    "merely to negate them",
    "identity and name lists",
    "keep the identity list scalar",
    "replace scalar entries with objects",
    "richer sibling information",
    "sentinel for true insufficient",
    "absent required schedule",
    "it does not",
    "become the applicable authority",
    "opaque contract values",
    "cross-artifact contract",
    "byte-for-byte unchanged",
    "cannot replace its traceability",
    "establish every input and output unit",
    "requested physical domain",
    "fit in raw coordinates is not correct",
    "heterogeneous source categories",
    "typed identity",
    "category:id",
    "group by the semantic category",
    "adjacent unrequested inputs",
    "later round",
    "every constraint introduced",
    "already-satisfied constraints",
    "meaningfully constructible",
    "reversible requested artifact",
    "material retry and recovery behavior",
    "bounded ephemeral producer",
    "independent effects",
    "at least three",
    "waiting, not periodic polling",
    "Optional richer provenance",
    "one-shot transient event",
    "repeated fixer work",
    "cannot stand in",
    "failed acceptance evidence",
    "measure the unchanged",
    "same representative workload",
    "structured or network response",
    "keys, counts",
    "complete nested metadata",
    "unseen same-class inputs",
    "calibration sample",
    "contract-preserving",
    "tuned constants",
    "deliverable accepts inputs beyond the supplied example",
    "example-derived constant",
    "independently created or independently selected input",
    "requirement-to-test ledger",
    "direct repository test",
    "hidden/external gates",
    "define forward progress",
    "repeated page or cursor token",
    "permanent client errors",
];

#[test]
fn embedded_workflow_carries_the_hard_source_limit_for_every_role() {
    for instructions in [architect(), developer(), reviewer()] {
        for term in REQUIRED_WORKFLOW_TERMS {
            assert!(instructions.contains(term), "missing required workflow term: {term}");
        }
    }
}
