use super::check_cargo_fixture as check;
use crate::model::{ArchitecturePolicy, PackagePolicy};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process;
use std::sync::atomic::{AtomicU64, Ordering};

static FIXTURE_ID: AtomicU64 = AtomicU64::new(0);

struct TestDirectory(PathBuf);

impl TestDirectory {
    fn new() -> Self {
        let id = FIXTURE_ID.fetch_add(1, Ordering::Relaxed);
        let path =
            env::temp_dir().join(format!("peritus-xtask-cargo-target-{}-{id}", process::id()));
        fs::create_dir_all(&path).expect("fixture directory must be created");
        Self(path)
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TestDirectory {
    fn drop(&mut self) {
        let _cleanup_result = fs::remove_dir_all(&self.0);
    }
}

fn policy() -> ArchitecturePolicy {
    ArchitecturePolicy {
        schema: 1,
        soft_source_lines: 400,
        hard_source_lines: 700,
        root_module_lines: 80,
        required_license: "MIT".to_owned(),
        ignored_directories: Vec::new(),
        forbidden_module_names: Vec::new(),
        trusted_source_roots: Vec::new(),
        source_exceptions: Vec::new(),
        layers: Vec::new(),
        verification_classes: Vec::new(),
        forbidden_dependencies: Vec::new(),
        controlled_source_roots: Vec::new(),
        packages: vec![PackagePolicy {
            name: "fixture".to_owned(),
            path: PathBuf::new(),
            owner: "A0".to_owned(),
            layer: "engineering".to_owned(),
            verification_class: "C".to_owned(),
        }],
    }
}

fn write(fixture: &TestDirectory, relative: &str, contents: &str) -> PathBuf {
    let path = fixture.path().join(relative);
    fs::create_dir_all(path.parent().expect("fixture source must have a parent"))
        .expect("fixture source directory must be created");
    fs::write(&path, contents).expect("fixture source must be written");
    path
}

fn write_cargo_package(fixture: &TestDirectory, target: &str) {
    write(
        fixture,
        "Cargo.toml",
        &format!(
            r#"[package]
name = "fixture"
version = "0.0.0"
edition = "2024"

[package.metadata.peritus]
owner = "A0"
layer = "engineering"
verification-class = "C"

{target}
"#,
        ),
    );
    write(
        fixture,
        "Cargo.lock",
        r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "fixture"
version = "0.0.0"
"#,
    );
}

#[test]
fn cargo_metadata_seeds_non_rust_target_roots() {
    let fixture = TestDirectory::new();
    write_cargo_package(&fixture, "[[bin]]\nname = \"fixture\"\npath = \"payload.txt\"");
    write(&fixture, "payload.txt", "proof fn hidden_target() { admit(); }\n");

    let error = check(fixture.path(), &policy())
        .expect_err("Cargo target roots must be trust-scanned regardless of extension");
    assert!(
        error.diagnostics().iter().any(|diagnostic| {
            diagnostic.path() == Some(Path::new("payload.txt"))
                && diagnostic.message().contains("admit")
        }),
        "{}",
        error.render()
    );
}

#[test]
fn cargo_metadata_rejects_target_roots_under_ignored_prefixes() {
    let fixture = TestDirectory::new();
    write_cargo_package(&fixture, "[[bin]]\nname = \"fixture\"\npath = \"target/hidden.txt\"");
    write(&fixture, "target/hidden.txt", "fn main() { let _ = (); }\n");
    let mut policy = policy();
    policy.ignored_directories.push("target".to_owned());

    let error = check(fixture.path(), &policy)
        .expect_err("ignored prefixes cannot provide Cargo target roots");
    assert!(
        error.diagnostics().iter().any(|diagnostic| {
            diagnostic.path() == Some(Path::new("target/hidden.txt"))
                && diagnostic.message().contains("ignored repository prefix")
        }),
        "{}",
        error.render()
    );
}

#[test]
fn rejects_workspace_procedural_macro_targets() {
    let fixture = TestDirectory::new();
    write_cargo_package(&fixture, "[lib]\nproc-macro = true\npath = \"generator.rs\"");
    write(
        &fixture,
        "generator.rs",
        r##"
extern crate proc_macro;
use proc_macro::TokenStream;

#[proc_macro]
pub fn hidden(_input: TokenStream) -> TokenStream {
    "#[verifier(external)] fn generated_trust() { let _ = (); }".parse().unwrap()
}
"##,
    );

    let error = check(fixture.path(), &policy())
        .expect_err("workspace procedural macros must fail closed at A0");
    assert!(error.diagnostics().iter().any(|diagnostic| {
        diagnostic.path() == Some(Path::new("generator.rs"))
            && diagnostic.message().contains("procedural-macro target")
            && diagnostic.help().contains("external pinned proc macros")
    }));
}

#[test]
fn rejects_workspace_build_script_targets_before_candidate_execution() {
    let fixture = TestDirectory::new();
    write_cargo_package(&fixture, "");
    write(&fixture, "src/lib.rs", "pub fn value() -> u8 { 1 }\n");
    write(
        &fixture,
        "build.rs",
        "fn main() { std::fs::write(\"src/lib.rs\", \"pub fn value() -> u8 { 2 }\\n\").unwrap(); }\n",
    );

    let error = check(fixture.path(), &policy())
        .expect_err("workspace build scripts must fail before Gate A executes candidate code");
    assert!(error.diagnostics().iter().any(|diagnostic| {
        diagnostic.path() == Some(Path::new("build.rs"))
            && diagnostic.message().contains("build-script target")
            && diagnostic.help().contains("separately isolated")
    }));
}
