//! Artifact and prompt-correlation field metadata.

use super::super::{AppTypeDescriptor, CanonicalWireType, FieldBound as B, JsonShape as J, field};

pub(super) const ARTIFACT_PROMPT_TYPES: &[AppTypeDescriptor] = &[
    AppTypeDescriptor {
        name: "ArtifactOpenRequest",
        rust_type: "ArtifactOpenRequest",
        fields: &[
            field(
                "transferId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "TransferId",
                "TransferId",
                J::Identifier,
                true,
            ),
            field(
                "artifactId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "ArtifactId",
                "ArtifactId",
                J::Identifier,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ArtifactMetadata",
        rust_type: "ArtifactMetadata",
        fields: &[
            field(
                "transferId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "TransferId",
                "TransferId",
                J::Identifier,
                true,
            ),
            field(
                "artifactId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "ArtifactId",
                "ArtifactId",
                J::Identifier,
                true,
            ),
            field(
                "byteSize",
                CanonicalWireType::U64,
                &[B::DeclaredArtifactSize],
                "u64",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "mediaType",
                CanonicalWireType::Utf8,
                &[B::CodecStringBytes],
                "CanonicalMediaType",
                "string",
                J::String,
                true,
            ),
            field(
                "digest",
                CanonicalWireType::Digest,
                &[],
                "Sha256Digest",
                "Sha256Digest",
                J::Digest,
                true,
            ),
            field(
                "preferredChunkSize",
                CanonicalWireType::U32,
                &[B::NonZero, B::ArtifactChunkBytes],
                "u32",
                "number",
                J::U32,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ArtifactChunk",
        rust_type: "ArtifactChunk",
        fields: &[
            field(
                "transferId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "TransferId",
                "TransferId",
                J::Identifier,
                true,
            ),
            field(
                "artifactId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "ArtifactId",
                "ArtifactId",
                J::Identifier,
                true,
            ),
            field(
                "ordinal",
                CanonicalWireType::U64,
                &[B::Contiguous],
                "u64",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "offset",
                CanonicalWireType::U64,
                &[B::Contiguous],
                "u64",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "bytes",
                CanonicalWireType::Bytes,
                &[B::ArtifactChunkBytes, B::DeclaredArtifactSize],
                "Vec<u8>",
                "Base64Bytes",
                J::Base64,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ArtifactCompletion",
        rust_type: "ArtifactCompletion",
        fields: &[
            field(
                "transferId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "TransferId",
                "TransferId",
                J::Identifier,
                true,
            ),
            field(
                "artifactId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "ArtifactId",
                "ArtifactId",
                J::Identifier,
                true,
            ),
            field(
                "byteSize",
                CanonicalWireType::U64,
                &[B::DeclaredArtifactSize],
                "u64",
                "UInt64",
                J::U64String,
                true,
            ),
            field(
                "digest",
                CanonicalWireType::Digest,
                &[],
                "Sha256Digest",
                "Sha256Digest",
                J::Digest,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "ArtifactCancellation",
        rust_type: "ArtifactCancellation",
        fields: &[
            field(
                "transferId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "TransferId",
                "TransferId",
                J::Identifier,
                true,
            ),
            field(
                "artifactId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "ArtifactId",
                "ArtifactId",
                J::Identifier,
                true,
            ),
            field(
                "correlationId",
                CanonicalWireType::Identifier,
                &[B::NonZero, B::EnvelopeBinding],
                "CorrelationId",
                "CorrelationId",
                J::Identifier,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "PromptCorrelation",
        rust_type: "PromptCorrelation",
        fields: &[
            field(
                "originatingRequestId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "RequestId",
                "RequestId",
                J::Identifier,
                true,
            ),
            field(
                "promptId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "PromptId",
                "PromptId",
                J::Identifier,
                true,
            ),
            field(
                "sessionId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "SessionId",
                "SessionId",
                J::Identifier,
                true,
            ),
            field(
                "actorId",
                CanonicalWireType::Identifier,
                &[B::NonZero],
                "ActorId",
                "ActorId",
                J::Identifier,
                true,
            ),
            field(
                "revision",
                CanonicalWireType::Struct,
                &[],
                "RevisionTuple",
                "RevisionTuple",
                J::Ref("RevisionTuple"),
                true,
            ),
            field(
                "freshnessDigest",
                CanonicalWireType::Digest,
                &[],
                "Sha256Digest",
                "Sha256Digest",
                J::Digest,
                true,
            ),
            field(
                "cancellationGeneration",
                CanonicalWireType::U64,
                &[B::NonZero],
                "Generation",
                "UInt64",
                J::U64String,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "PromptChoice",
        rust_type: "PromptChoice",
        fields: &[
            field(
                "id",
                CanonicalWireType::Utf8,
                &[B::NonZero, B::CodecStringBytes],
                "String",
                "string",
                J::String,
                true,
            ),
            field(
                "label",
                CanonicalWireType::Utf8,
                &[B::NonZero, B::CodecStringBytes],
                "String",
                "string",
                J::String,
                true,
            ),
        ],
    },
    AppTypeDescriptor {
        name: "PromptConstraint",
        rust_type: "PromptConstraint",
        fields: &[
            field(
                "kind",
                CanonicalWireType::U8,
                &[],
                "PromptConstraint",
                "\"non-empty\" | \"maximum-text-bytes\" | \"bound-choice-only\" | \"secret-reference\"",
                J::Enum(&[
                    "non-empty",
                    "maximum-text-bytes",
                    "bound-choice-only",
                    "secret-reference",
                ]),
                true,
            ),
            field(
                "maximumTextBytes",
                CanonicalWireType::U32,
                &[B::CodecStringBytes],
                "Option<u32>",
                "number",
                J::U32,
                false,
            ),
        ],
    },
];
